Running doctests with ID 2018-03-07-14-55-34-440a20b6.
Using --optional=gmp,sage
Doctesting entire Sage library.
Sorting sources by runtime so that slower doctests are run first....
Doctesting 3587 files using 4 threads.
    Timed out
**********************************************************************
Tests run before process (pid=20434) timed out:
sage: doctest_var = 42; doctest_var^2 ## line 11 ##
1764
sage: R.<a> = ZZ[] ## line 13 ##
sage: a + doctest_var ## line 14 ##
a + 42
sage: sig_on_count() # check sig_on/off pairings (virtual doctest) ## line 22 ##
0
sage: from sage.doctest.forker import init_sage ## line 66 ##
sage: sage.doctest.DOCTEST_MODE = False ## line 67 ##
sage: init_sage() ## line 68 ##
sage: sage.doctest.DOCTEST_MODE ## line 69 ##
True
sage: gap.eval("my_test_var := 42;") ## line 74 ##
'42'
sage: gap.eval("my_test_var;") ## line 76 ##
'42'
sage: init_sage() ## line 78 ##
sage: gap('Group((1,2,3)(4,5), (3,4))') ## line 79 ##
Group( [ (1,2,3)(4,5), (3,4) ] )
sage: gap.eval("my_test_var;") ## line 81 ##
sage: from sympy import sympify ## line 89 ##
sage: from sympy.printing.pretty.pretty import PrettyPrinter ## line 90 ##
sage: s = sympify('+x^'.join(str(i) for i in range(30))) ## line 91 ##
sage: print(PrettyPrinter(settings={'wrap_line':True}).doprint(s)) ## line 92 ##
 29    28    27    26    25    24    23    22    21    20    19    18    17   
x   + x   + x   + x   + x   + x   + x   + x   + x   + x   + x   + x   + x   + 

 16    15    14    13    12    11    10    9    8    7    6    5    4    3    
x   + x   + x   + x   + x   + x   + x   + x  + x  + x  + x  + x  + x  + x  + x

2    
  + x
sage: {'a':23, 'b':34, 'au':56, 'bbf':234, 'aaa':234} ## line 105 ##
{'a': 23, 'aaa': 234, 'au': 56, 'b': 34, 'bbf': 234}
sage: sig_on_count() # check sig_on/off pairings (virtual doctest) ## line 107 ##
0
sage: from sage.doctest.forker import showwarning_with_traceback ## line 149 ##
sage: showwarning_with_traceback("bad stuff", UserWarning, "myfile.py", 0) ## line 150 ##
doctest:warning
  File "/nix/store/zgb4cibb5vx07j4gr892mfcxzcjmdrgw-sage-src-8.1/src/bin/sage-runtests", line 125, in <module>
    err = DC.run()
  File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/doctest/control.py", line 1126, in run
    self.run_doctests()
  File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/doctest/control.py", line 854, in run_doctests
    self.dispatcher.dispatch()
  File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/doctest/forker.py", line 1774, in dispatch
    self.parallel_dispatch()
  File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/doctest/forker.py", line 1664, in parallel_dispatch
    w.start()  # This might take some time
  File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/doctest/forker.py", line 1940, in start
    super(DocTestWorker, self).start()
  File "/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/python2.7/multiprocessing/process.py", line 130, in start
    self._popen = Popen(self)
  File "/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/python2.7/multiprocessing/forking.py", line 126, in __init__
    code = process_obj._bootstrap()
  File "/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/doctest/forker.py", line 1913, in run
    task(self.options, self.outtmpfile, msgpipe, self.result_queue)
  File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/doctest/forker.py", line 2215, in __call__
    result = runner.run(test)
  File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/doctest/forker.py", line 660, in run
    return self._run(test, compileflags, out)
  File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/doctest/forker.py", line 515, in _run
    self.compile_and_execute(example, compiler, test.globs)
  File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/doctest/forker.py", line 885, in compile_and_execute
    exec(compiled, globs)
  File "<doctest sage.doctest.forker.showwarning_with_traceback[1]>", line 1, in <module>
    showwarning_with_traceback("bad stuff", UserWarning, "myfile.py", Integer(0))
:
UserWarning: bad stuff
sage: sig_on_count() # check sig_on/off pairings (virtual doctest) ## line 157 ##
0
sage: import subprocess, tempfile ## line 196 ##
sage: from sage.doctest.forker import SageSpoofInOut ## line 197 ##
sage: O = tempfile.TemporaryFile() ## line 198 ##
sage: S = SageSpoofInOut(O) ## line 199 ##
sage: try:
    S.start_spoofing()
    print("hello world")
finally:
    S.stop_spoofing() ## line 200 ##
sage: S.getvalue() ## line 206 ##
'hello world\n'
sage: O.seek(0) ## line 208 ##
sage: S = SageSpoofInOut(outfile=sys.stdout, infile=O) ## line 209 ##
sage: try:
    S.start_spoofing()
    _ = subprocess.check_call("cat")
finally:
    S.stop_spoofing() ## line 210 ##
hello world
sage: sig_on_count() # check sig_on/off pairings (virtual doctest) ## line 217 ##
0
sage: import tempfile ## line 224 ##
sage: from sage.doctest.forker import SageSpoofInOut ## line 225 ##
sage: SageSpoofInOut(tempfile.TemporaryFile(), tempfile.TemporaryFile()) ## line 226 ##
<class 'sage.doctest.forker.SageSpoofInOut'>
sage: sig_on_count() # check sig_on/off pairings (virtual doctest) ## line 228 ##
0
sage: from sage.doctest.forker import SageSpoofInOut ## line 249 ##
sage: spoof = SageSpoofInOut() ## line 250 ##
sage: spoof.start_spoofing() ## line 251 ##
sage: print("Not spoofed!") ## line 254 ##
Not spoofed!
sage: sig_on_count() # check sig_on/off pairings (virtual doctest) ## line 256 ##
0
sage: import os, tempfile ## line 266 ##
sage: from sage.doctest.forker import SageSpoofInOut ## line 267 ##
sage: O = tempfile.TemporaryFile() ## line 268 ##
sage: S = SageSpoofInOut(O) ## line 269 ##
sage: try:
    S.start_spoofing()
    print("this is not printed")
finally:
    S.stop_spoofing() ## line 270 ##
sage: S.getvalue() ## line 276 ##
'this is not printed\n'
sage: O.seek(0) ## line 278 ##
sage: S = SageSpoofInOut(infile=O) ## line 279 ##
sage: try:
    S.start_spoofing()
    v = sys.stdin.read()
finally:
    S.stop_spoofing() ## line 280 ##
sage: v ## line 286 ##
'this is not printed\n'
sage: try:
    S.start_spoofing()
    retval = os.system('''echo "Hello there"\nif [ $? -eq 0 ]; then\necho "good"\nfi''')
finally:
    S.stop_spoofing() ## line 291 ##
sage: S.getvalue() ## line 297 ##
'Hello there\ngood\n'
sage: sig_on_count() # check sig_on/off pairings (virtual doctest) ## line 299 ##
0
sage: from sage.doctest.forker import SageSpoofInOut ## line 315 ##
sage: S = SageSpoofInOut() ## line 316 ##
sage: try:
    S.start_spoofing()
    print("this is not printed")
finally:
    S.stop_spoofing() ## line 317 ##
sage: print("this is now printed") ## line 323 ##
this is now printed
sage: sig_on_count() # check sig_on/off pairings (virtual doctest) ## line 325 ##
0
sage: from sage.doctest.forker import SageSpoofInOut ## line 343 ##
sage: S = SageSpoofInOut() ## line 344 ##
sage: try:
    S.start_spoofing()
    print("step 1")
finally:
    S.stop_spoofing() ## line 345 ##
sage: S.getvalue() ## line 351 ##
'step 1\n'
sage: try:
    S.start_spoofing()
    print("step 2")
finally:
    S.stop_spoofing() ## line 353 ##
sage: S.getvalue() ## line 359 ##
'step 2\n'
sage: sig_on_count() # check sig_on/off pairings (virtual doctest) ## line 361 ##
0
sage: from sage.doctest.parsing import SageOutputChecker ## line 392 ##
sage: from sage.doctest.forker import SageDocTestRunner ## line 393 ##
sage: from sage.doctest.control import DocTestDefaults; DD = DocTestDefaults() ## line 394 ##
sage: import doctest, sys, os ## line 395 ##
sage: DTR = SageDocTestRunner(SageOutputChecker(), verbose=False, sage_options=DD, optionflags=doctest.NORMALIZE_WHITESPACE|doctest.ELLIPSIS) ## line 396 ##
sage: DTR ## line 397 ##
<sage.doctest.forker.SageDocTestRunner instance at 0x7ff35257f998>
sage: sig_on_count() # check sig_on/off pairings (virtual doctest) ## line 399 ##
0
sage: from sage.doctest.parsing import SageOutputChecker ## line 430 ##
sage: from sage.doctest.forker import SageDocTestRunner ## line 431 ##
sage: from sage.doctest.sources import FileDocTestSource ## line 432 ##
sage: from sage.doctest.control import DocTestDefaults; DD = DocTestDefaults() ## line 433 ##
sage: from sage.env import SAGE_SRC ## line 434 ##
sage: import doctest, sys, os ## line 435 ##
sage: DTR = SageDocTestRunner(SageOutputChecker(), verbose=False, sage_options=DD, optionflags=doctest.NORMALIZE_WHITESPACE|doctest.ELLIPSIS) ## line 436 ##
sage: filename = os.path.join(SAGE_SRC,'sage','doctest','forker.py') ## line 437 ##
sage: FDS = FileDocTestSource(filename,DD) ## line 438 ##
sage: doctests, extras = FDS.create_doctests(globals()) ## line 439 ##
sage: DTR.run(doctests[0], clear_globs=False) # indirect doctest ## line 440 ##
TestResults(failed=0, attempted=4)
sage: sig_on_count() # check sig_on/off pairings (virtual doctest) ## line 442 ##
0
sage: from sage.doctest.parsing import SageOutputChecker ## line 619 ##
sage: from sage.doctest.forker import SageDocTestRunner ## line 620 ##
sage: from sage.doctest.sources import FileDocTestSource ## line 621 ##
sage: from sage.doctest.control import DocTestDefaults; DD = DocTestDefaults() ## line 622 ##
sage: from sage.env import SAGE_SRC ## line 623 ##
sage: import doctest, sys, os ## line 624 ##
sage: DTR = SageDocTestRunner(SageOutputChecker(), verbose=False, sage_options=DD, optionflags=doctest.NORMALIZE_WHITESPACE|doctest.ELLIPSIS) ## line 625 ##
sage: filename = os.path.join(SAGE_SRC,'sage','doctest','forker.py') ## line 626 ##
sage: FDS = FileDocTestSource(filename,DD) ## line 627 ##
sage: doctests, extras = FDS.create_doctests(globals()) ## line 628 ##
sage: DTR.run(doctests[0], clear_globs=False) ## line 629 ##
TestResults(failed=0, attempted=4)
sage: sig_on_count() # check sig_on/off pairings (virtual doctest) ## line 631 ##
0
sage: from sage.doctest.parsing import SageOutputChecker ## line 684 ##
sage: from sage.doctest.forker import SageDocTestRunner ## line 685 ##
sage: from sage.doctest.control import DocTestDefaults; DD = DocTestDefaults() ## line 686 ##
sage: import doctest, sys, os ## line 687 ##
sage: DTR = SageDocTestRunner(SageOutputChecker(), verbose=False, sage_options=DD, optionflags=doctest.NORMALIZE_WHITESPACE|doctest.ELLIPSIS) ## line 688 ##
sage: DTR._name2ft['sage.doctest.forker'] = (1,120) ## line 689 ##
sage: results = DTR.summarize() ## line 690 ##
**********************************************************************
1 item had failures:
   1 of 120 in sage.doctest.forker
sage: results ## line 694 ##
TestResults(failed=1, attempted=120)
sage: sig_on_count() # check sig_on/off pairings (virtual doctest) ## line 696 ##
0
sage: R.<x> = ZZ[] ## line 750 ##
sage: f = x^2 + 1 ## line 751 ##
sage: from sage.doctest.parsing import SageOutputChecker ## line 766 ##
sage: from sage.doctest.forker import SageDocTestRunner ## line 767 ##
sage: from sage.doctest.sources import FileDocTestSource ## line 768 ##
sage: from sage.doctest.control import DocTestDefaults; DD = DocTestDefaults() ## line 769 ##
sage: from sage.env import SAGE_SRC ## line 770 ##
sage: import doctest, sys, os, hashlib ## line 771 ##
sage: DTR = SageDocTestRunner(SageOutputChecker(), verbose=False, sage_options=DD, optionflags=doctest.NORMALIZE_WHITESPACE|doctest.ELLIPSIS) ## line 772 ##
sage: filename = os.path.join(SAGE_SRC,'sage','doctest','forker.py') ## line 773 ##
sage: FDS = FileDocTestSource(filename,DD) ## line 774 ##
sage: doctests, extras = FDS.create_doctests(globals()) ## line 775 ##
sage: DTR.running_global_digest.hexdigest() ## line 776 ##
'd41d8cd98f00b204e9800998ecf8427e'
sage: DTR.running_doctest_digest = hashlib.md5() ## line 778 ##
sage: ex = doctests[0].examples[0]; ex.predecessors = None ## line 779 ##
sage: DTR.update_digests(ex) ## line 780 ##
sage: DTR.running_global_digest.hexdigest() ## line 781 ##
'3cb44104292c3a3ab4da3112ce5dc35c'
sage: sig_on_count() # check sig_on/off pairings (virtual doctest) ## line 783 ##
0
sage: R.<x> = ZZ[] ## line 803 ##
sage: f = x^2 + 1 ## line 804 ##
sage: from sage.doctest.parsing import SageOutputChecker ## line 826 ##
sage: from sage.doctest.forker import SageDocTestRunner ## line 827 ##
sage: from sage.doctest.sources import FileDocTestSource ## line 828 ##
sage: from sage.doctest.util import RecordingDict ## line 829 ##
sage: from sage.doctest.control import DocTestDefaults; DD = DocTestDefaults() ## line 830 ##
sage: from sage.env import SAGE_SRC ## line 831 ##
sage: import doctest, sys, os, hashlib ## line 832 ##
sage: DTR = SageDocTestRunner(SageOutputChecker(), verbose=False, sage_options=DD, optionflags=doctest.NORMALIZE_WHITESPACE|doctest.ELLIPSIS) ## line 833 ##
sage: DTR.running_doctest_digest = hashlib.md5() ## line 834 ##
sage: filename = os.path.join(SAGE_SRC,'sage','doctest','forker.py') ## line 835 ##
sage: FDS = FileDocTestSource(filename,DD) ## line 836 ##
sage: globs = RecordingDict(globals()) ## line 837 ##
sage: 'doctest_var' in globs ## line 838 ##
False
sage: doctests, extras = FDS.create_doctests(globs) ## line 840 ##
sage: ex0 = doctests[0].examples[0] ## line 841 ##
sage: compiler = lambda ex: compile(ex.source, '<doctest sage.doctest.forker[0]>', 'single', 32768, 1) ## line 842 ##
sage: DTR.compile_and_execute(ex0, compiler, globs) ## line 843 ##
1764
sage: globs['doctest_var'] ## line 845 ##
42
sage: globs.set ## line 847 ##
{'doctest_var'}
sage: globs.got ## line 849 ##
{'Integer'}
sage: ex1 = doctests[0].examples[1] ## line 854 ##
sage: compiler = lambda ex:compile(ex.source, '<doctest sage.doctest.forker[1]>', 'single', 32768, 1) ## line 855 ##
sage: DTR.compile_and_execute(ex1, compiler, globs) ## line 856 ##
sage: sorted(list(globs.set)) ## line 857 ##
['R', 'a']
sage: globs.got ## line 859 ##
{'ZZ'}
sage: ex1.predecessors ## line 861 ##
[]
sage: ex2 = doctests[0].examples[2] ## line 866 ##
sage: compiler = lambda ex:compile(ex.source, '<doctest sage.doctest.forker[2]>', 'single', 32768, 1) ## line 867 ##
sage: DTR.compile_and_execute(ex2, compiler, globs) ## line 868 ##
a + 42
sage: list(globs.set) ## line 870 ##
[]
sage: sorted(list(globs.got)) ## line 872 ##
['a', 'doctest_var']
sage: set(ex2.predecessors) == set([ex0,ex1]) ## line 874 ##
True
sage: sig_on_count() # check sig_on/off pairings (virtual doctest) ## line 876 ##
0
sage: from sage.doctest.parsing import SageOutputChecker ## line 920 ##
sage: from sage.doctest.forker import SageDocTestRunner ## line 921 ##
sage: from sage.doctest.sources import FileDocTestSource ## line 922 ##
sage: from sage.doctest.control import DocTestDefaults; DD = DocTestDefaults() ## line 923 ##
sage: from sage.env import SAGE_SRC ## line 924 ##
sage: import doctest, sys, os ## line 925 ##
sage: DTR = SageDocTestRunner(SageOutputChecker(), verbose=False, sage_options=DD, optionflags=doctest.NORMALIZE_WHITESPACE|doctest.ELLIPSIS) ## line 926 ##
sage: filename = os.path.join(SAGE_SRC,'sage','doctest','forker.py') ## line 927 ##
sage: FDS = FileDocTestSource(filename,DD) ## line 928 ##
sage: doctests, extras = FDS.create_doctests(globals()) ## line 929 ##
sage: ex = doctests[0].examples[0] ## line 930 ##
sage: print(DTR._failure_header(doctests[0], ex)) ## line 931 ##
**********************************************************************
File "/nix/store/zgb4cibb5vx07j4gr892mfcxzcjmdrgw-sage-src-8.1/src/sage/doctest/forker.py", line 11, in sage.doctest.forker
Failed example:
    doctest_var = 42; doctest_var^2

sage: import doctest ## line 940 ##
sage: print(doctest.DocTestRunner._failure_header(DTR, doctests[0], ex)) ## line 941 ##
**********************************************************************
File "/nix/store/zgb4cibb5vx07j4gr892mfcxzcjmdrgw-sage-src-8.1/src/sage/doctest/forker.py", line 11, in sage.doctest.forker
Failed example:
    doctest_var = Integer(42); doctest_var**Integer(2)

sage: print(DTR._failure_header(doctests[0], ex, message='Hello there!')) ## line 950 ##
**********************************************************************
File "/nix/store/zgb4cibb5vx07j4gr892mfcxzcjmdrgw-sage-src-8.1/src/sage/doctest/forker.py", line 11, in sage.doctest.forker
Hello there!
    doctest_var = 42; doctest_var^2

sage: sig_on_count() # check sig_on/off pairings (virtual doctest) ## line 956 ##
0
sage: from sage.doctest.parsing import SageOutputChecker ## line 991 ##
sage: from sage.doctest.forker import SageDocTestRunner ## line 992 ##
sage: from sage.doctest.sources import FileDocTestSource ## line 993 ##
sage: from sage.doctest.control import DocTestDefaults; DD = DocTestDefaults() ## line 994 ##
sage: from sage.env import SAGE_SRC ## line 995 ##
sage: import doctest, sys, os ## line 996 ##
sage: DTR = SageDocTestRunner(SageOutputChecker(), verbose=True, sage_options=DD, optionflags=doctest.NORMALIZE_WHITESPACE|doctest.ELLIPSIS) ## line 997 ##
sage: filename = os.path.join(SAGE_SRC,'sage','doctest','forker.py') ## line 998 ##
sage: FDS = FileDocTestSource(filename,DD) ## line 999 ##
sage: doctests, extras = FDS.create_doctests(globals()) ## line 1000 ##
sage: ex = doctests[0].examples[0] ## line 1001 ##
sage: DTR.report_start(sys.stdout.write, doctests[0], ex) ## line 1002 ##
Trying (line 11):    doctest_var = 42; doctest_var^2
Expecting:
    1764
sage: sig_on_count() # check sig_on/off pairings (virtual doctest) ## line 1006 ##
0
sage: from sage.doctest.parsing import SageOutputChecker ## line 1041 ##
sage: from sage.doctest.forker import SageDocTestRunner ## line 1042 ##
sage: from sage.doctest.sources import FileDocTestSource ## line 1043 ##
sage: from sage.doctest.control import DocTestDefaults; DD = DocTestDefaults() ## line 1044 ##
sage: from sage.misc.misc import walltime ## line 1045 ##
sage: from sage.env import SAGE_SRC ## line 1046 ##
sage: import doctest, sys, os ## line 1047 ##
sage: DTR = SageDocTestRunner(SageOutputChecker(), verbose=True, sage_options=DD, optionflags=doctest.NORMALIZE_WHITESPACE|doctest.ELLIPSIS) ## line 1048 ##
sage: filename = os.path.join(SAGE_SRC,'sage','doctest','forker.py') ## line 1049 ##
sage: FDS = FileDocTestSource(filename,DD) ## line 1050 ##
sage: doctests, extras = FDS.create_doctests(globals()) ## line 1051 ##
sage: ex = doctests[0].examples[0] ## line 1052 ##
sage: ex.walltime = 0.0 ## line 1053 ##
sage: DTR.report_success(sys.stdout.write, doctests[0], ex, '1764') ## line 1054 ##
ok [0.00 s]
sage: sig_on_count() # check sig_on/off pairings (virtual doctest) ## line 1056 ##
0
sage: from sage.doctest.parsing import SageOutputChecker ## line 1083 ##
sage: from sage.doctest.forker import SageDocTestRunner ## line 1084 ##
sage: from sage.doctest.sources import FileDocTestSource ## line 1085 ##
sage: from sage.doctest.control import DocTestDefaults; DD = DocTestDefaults() ## line 1086 ##
sage: from sage.env import SAGE_SRC ## line 1087 ##
sage: import doctest, sys, os ## line 1088 ##
sage: DTR = SageDocTestRunner(SageOutputChecker(), verbose=True, sage_options=DD, optionflags=doctest.NORMALIZE_WHITESPACE|doctest.ELLIPSIS) ## line 1089 ##
sage: filename = os.path.join(SAGE_SRC,'sage','doctest','forker.py') ## line 1090 ##
sage: FDS = FileDocTestSource(filename,DD) ## line 1091 ##
sage: doctests, extras = FDS.create_doctests(globals()) ## line 1092 ##
sage: ex = doctests[0].examples[0] ## line 1093 ##
sage: DTR.no_failure_yet = True ## line 1094 ##
sage: DTR.report_failure(sys.stdout.write, doctests[0], ex, 'BAD ANSWER\n', {}) ## line 1095 ##
**********************************************************************
File "/nix/store/zgb4cibb5vx07j4gr892mfcxzcjmdrgw-sage-src-8.1/src/sage/doctest/forker.py", line 11, in sage.doctest.forker
Failed example:
    doctest_var = 42; doctest_var^2
Expected:
    1764
Got:
    BAD ANSWER
sage: import os ## line 1108 ##
sage: os.environ['SAGE_PEXPECT_LOG'] = "1" ## line 1109 ##
sage: sage0.quit() ## line 1110 ##
sage: _ = sage0.eval("import doctest, sys, os, multiprocessing, subprocess") ## line 1111 ##
------------------------------------------------------------------------
/nix/store/bprqv413l2r68dp3m6y7i693zpzjsjnp-spkg-cysignals-1.6.5/lib/python2.7/site-packages/cysignals/signals.so(+0x53c7)[0x7ff3c98dd3c7]
/nix/store/bprqv413l2r68dp3m6y7i693zpzjsjnp-spkg-cysignals-1.6.5/lib/python2.7/site-packages/cysignals/signals.so(+0x5f55)[0x7ff3c98ddf55]
/nix/store/bprqv413l2r68dp3m6y7i693zpzjsjnp-spkg-cysignals-1.6.5/lib/python2.7/site-packages/cysignals/signals.so(+0x87d7)[0x7ff3c98e07d7]
/nix/store/2kcrj1ksd2a14bm5sky182fv2xwfhfap-glibc-2.26-131/lib/libc.so.6(+0x342d0)[0x7ff3cdf8a2d0]
/nix/store/2kcrj1ksd2a14bm5sky182fv2xwfhfap-glibc-2.26-131/lib/libc.so.6(__select+0x17)[0x7ff3ce03e567]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/python2.7/lib-dynload/select.so(+0x337c)[0x7ff3c864237c]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x74e6)[0x7ff3ced59416]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(+0x6e11d)[0x7ff3cece711d]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyObject_Call+0x43)[0x7ff3cecc3233]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x285d)[0x7ff3ced5478d]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(+0x6e11d)[0x7ff3cece711d]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyObject_Call+0x43)[0x7ff3cecc3233]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(+0x58b7c)[0x7ff3cecd1b7c]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyObject_Call+0x43)[0x7ff3cecc3233]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x285d)[0x7ff3ced5478d]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCode+0x19)[0x7ff3ced5b8f9]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x5cad)[0x7ff3ced57bdd]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(+0x6e039)[0x7ff3cece7039]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyObject_Call+0x43)[0x7ff3cecc3233]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(+0x58b7c)[0x7ff3cecd1b7c]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyObject_Call+0x43)[0x7ff3cecc3233]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(+0xa0f93)[0x7ff3ced19f93]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyObject_Call+0x43)[0x7ff3cecc3233]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x18d3)[0x7ff3ced53803]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x792a)[0x7ff3ced5985a]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(+0x6e039)[0x7ff3cece7039]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyObject_Call+0x43)[0x7ff3cecc3233]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(+0x58b7c)[0x7ff3cecd1b7c]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyObject_Call+0x43)[0x7ff3cecc3233]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(+0xa0c83)[0x7ff3ced19c83]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(+0x9d58a)[0x7ff3ced1658a]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyObject_Call+0x43)[0x7ff3cecc3233]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x18d3)[0x7ff3ced53803]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x792a)[0x7ff3ced5985a]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCode+0x19)[0x7ff3ced5b8f9]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(+0xfb38b)[0x7ff3ced7438b]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyRun_FileExFlags+0x72)[0x7ff3ced754c2]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyRun_SimpleFileExFlags+0xe3)[0x7ff3ced76613]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(Py_Main+0xb4a)[0x7ff3ced880ba]
/nix/store/2kcrj1ksd2a14bm5sky182fv2xwfhfap-glibc-2.26-131/lib/libc.so.6(__libc_start_main+0xf0)[0x7ff3cdf77020]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/bin/python(_start+0x2a)[0x4007aa]
------------------------------------------------------------------------
Attaching gdb to process id 20434.
Cannot find gdb installed
GDB is not installed.
Install gdb for enhanced tracebacks.
------------------------------------------------------------------------

**********************************************************************
    Timed out
**********************************************************************
Tests run before process (pid=20436) timed out:
sage: s = Sage() ## line 54 ##
sage: a = s(2) ## line 60 ##
------------------------------------------------------------------------
/nix/store/bprqv413l2r68dp3m6y7i693zpzjsjnp-spkg-cysignals-1.6.5/lib/python2.7/site-packages/cysignals/signals.so(+0x53c7)[0x7ff3c98dd3c7]
/nix/store/bprqv413l2r68dp3m6y7i693zpzjsjnp-spkg-cysignals-1.6.5/lib/python2.7/site-packages/cysignals/signals.so(+0x5f55)[0x7ff3c98ddf55]
/nix/store/bprqv413l2r68dp3m6y7i693zpzjsjnp-spkg-cysignals-1.6.5/lib/python2.7/site-packages/cysignals/signals.so(+0x87d7)[0x7ff3c98e07d7]
/nix/store/2kcrj1ksd2a14bm5sky182fv2xwfhfap-glibc-2.26-131/lib/libpthread.so.0(+0x11dd0)[0x7ff3cea6cdd0]
/nix/store/2kcrj1ksd2a14bm5sky182fv2xwfhfap-glibc-2.26-131/lib/libc.so.6(__select+0x17)[0x7ff3ce03e567]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/python2.7/lib-dynload/select.so(+0x337c)[0x7ff3c864237c]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x74e6)[0x7ff3ced59416]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(+0x6e039)[0x7ff3cece7039]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyObject_Call+0x43)[0x7ff3cecc3233]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(+0x58b7c)[0x7ff3cecd1b7c]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyObject_Call+0x43)[0x7ff3cecc3233]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(+0xa0f93)[0x7ff3ced19f93]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyObject_Call+0x43)[0x7ff3cecc3233]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x18d3)[0x7ff3ced53803]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCode+0x19)[0x7ff3ced5b8f9]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x5cad)[0x7ff3ced57bdd]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(+0x6e039)[0x7ff3cece7039]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyObject_Call+0x43)[0x7ff3cecc3233]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(+0x58b7c)[0x7ff3cecd1b7c]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyObject_Call+0x43)[0x7ff3cecc3233]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(+0xa0f93)[0x7ff3ced19f93]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyObject_Call+0x43)[0x7ff3cecc3233]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x18d3)[0x7ff3ced53803]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x792a)[0x7ff3ced5985a]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(+0x6e039)[0x7ff3cece7039]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyObject_Call+0x43)[0x7ff3cecc3233]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(+0x58b7c)[0x7ff3cecd1b7c]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyObject_Call+0x43)[0x7ff3cecc3233]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(+0xa0c83)[0x7ff3ced19c83]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(+0x9d58a)[0x7ff3ced1658a]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyObject_Call+0x43)[0x7ff3cecc3233]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x18d3)[0x7ff3ced53803]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x792a)[0x7ff3ced5985a]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCode+0x19)[0x7ff3ced5b8f9]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(+0xfb38b)[0x7ff3ced7438b]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyRun_FileExFlags+0x72)[0x7ff3ced754c2]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyRun_SimpleFileExFlags+0xe3)[0x7ff3ced76613]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(Py_Main+0xb4a)[0x7ff3ced880ba]
/nix/store/2kcrj1ksd2a14bm5sky182fv2xwfhfap-glibc-2.26-131/lib/libc.so.6(__libc_start_main+0xf0)[0x7ff3cdf77020]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/bin/python(_start+0x2a)[0x4007aa]
------------------------------------------------------------------------
Attaching gdb to process id 20436.
Cannot find gdb installed
GDB is not installed.
Install gdb for enhanced tracebacks.
------------------------------------------------------------------------

**********************************************************************
    Timed out
**********************************************************************
Tests run before process (pid=20437) timed out:
sage: K.<x> = QQ[] ## line 28 ##
sage: G = PermutationGroup([[(1,2,3),(4,5)], [(1,2)]]) ## line 29 ##
sage: rgp = Gp() ## line 30 ##
sage: def gap_randstring(n):
    current_randstate().set_seed_gap()
    return gap(n).SCRRandomString() ## line 31 ##
sage: def rtest():
    current_randstate().set_seed_gp(rgp)
    return (ZZ.random_element(1000), RR.random_element(),
            K.random_element(), G.random_element(),
            gap_randstring(5),
            rgp.random(), ntl.ZZ_random(99999),
            random()) ## line 34 ##
sage: set_random_seed(0) ## line 56 ##
sage: rtest() ## line 57 ##
(303,
 -0.266166246380421,
 1/2*x^2 - 1/95*x - 1/2,
 (1,3),
 [ 0, 0, 0, 0, 1 ],
 265625921,
 5842,
 0.9661911734708414)
sage: set_random_seed(1) ## line 59 ##
sage: rtest() ## line 60 ##
(978,
 0.0557699430711638,
 -3*x^2 - 1/12,
 (1,2),
 [ 0, 1, 1, 0, 0 ],
 807447831,
 29982,
 0.8335077654199736)
sage: set_random_seed(2) ## line 62 ##
sage: rtest() ## line 63 ##
(207,
 -0.0141049486533456,
 4*x^2 + 1/2,
 (1,2)(4,5),
 [ 0, 0, 1, 0, 1 ],
 1642898426,
 41662,
 0.19982565117278328)
sage: set_random_seed(0) ## line 65 ##
sage: rtest() ## line 66 ##
(303,
 -0.266166246380421,
 1/2*x^2 - 1/95*x - 1/2,
 (1,3),
 [ 0, 0, 0, 0, 1 ],
 265625921,
 5842,
 0.9661911734708414)
sage: set_random_seed(1) ## line 68 ##
sage: rtest() ## line 69 ##
(978,
 0.0557699430711638,
 -3*x^2 - 1/12,
 (1,2),
 [ 0, 1, 1, 0, 0 ],
 807447831,
 29982,
 0.8335077654199736)
sage: set_random_seed(2) ## line 71 ##
sage: rtest() ## line 72 ##
(207,
 -0.0141049486533456,
 4*x^2 + 1/2,
 (1,2)(4,5),
 [ 0, 0, 1, 0, 1 ],
 1642898426,
 41662,
 0.19982565117278328)
sage: set_random_seed(12345) ## line 79 ##
sage: initial_seed() ## line 80 ##
12345L
sage: rtest() ## line 82 ##
(720,
 -0.612180244315804,
 x^2 - x,
 (1,2,3),
 [ 1, 0, 0, 0, 0 ],
 1911581957,
 27093,
 0.9205331599518184)
sage: initial_seed() ## line 84 ##
12345L
sage: set_random_seed() ## line 98 ##
sage: r = rtest() ## line 99 ##
sage: r         # random ## line 100 ##
(826,
 -0.222777768544544,
 2*x^2 + 2*x,
 (1,2),
 [ 0, 1, 1, 0, 1 ],
 80065607,
 5587,
 0.1315704750812734)
sage: s = initial_seed() ## line 108 ##
sage: s         # random ## line 109 ##
294917007465971974047154458851121818947L
sage: set_random_seed(s) ## line 111 ##
sage: r2 = rtest() ## line 112 ##
sage: r == r2 ## line 113 ##
True
sage: subsage = Sage() ## line 127 ##
sage: s = ZZ(subsage('initial_seed()')) ## line 128 ##
------------------------------------------------------------------------
/nix/store/bprqv413l2r68dp3m6y7i693zpzjsjnp-spkg-cysignals-1.6.5/lib/python2.7/site-packages/cysignals/signals.so(+0x53c7)[0x7ff3c98dd3c7]
/nix/store/bprqv413l2r68dp3m6y7i693zpzjsjnp-spkg-cysignals-1.6.5/lib/python2.7/site-packages/cysignals/signals.so(+0x5f55)[0x7ff3c98ddf55]
/nix/store/bprqv413l2r68dp3m6y7i693zpzjsjnp-spkg-cysignals-1.6.5/lib/python2.7/site-packages/cysignals/signals.so(+0x87d7)[0x7ff3c98e07d7]
/nix/store/2kcrj1ksd2a14bm5sky182fv2xwfhfap-glibc-2.26-131/lib/libpthread.so.0(+0x11dd0)[0x7ff3cea6cdd0]
/nix/store/2kcrj1ksd2a14bm5sky182fv2xwfhfap-glibc-2.26-131/lib/libc.so.6(__select+0x17)[0x7ff3ce03e567]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/python2.7/lib-dynload/select.so(+0x337c)[0x7ff3c864237c]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x74e6)[0x7ff3ced59416]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(+0x6e11d)[0x7ff3cece711d]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyObject_Call+0x43)[0x7ff3cecc3233]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x285d)[0x7ff3ced5478d]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(+0x6e11d)[0x7ff3cece711d]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyObject_Call+0x43)[0x7ff3cecc3233]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(+0x58b7c)[0x7ff3cecd1b7c]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyObject_Call+0x43)[0x7ff3cecc3233]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x285d)[0x7ff3ced5478d]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(+0x6e039)[0x7ff3cece7039]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyObject_Call+0x43)[0x7ff3cecc3233]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(+0x58b7c)[0x7ff3cecd1b7c]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyObject_Call+0x43)[0x7ff3cecc3233]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(+0xa0c83)[0x7ff3ced19c83]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(+0x9d58a)[0x7ff3ced1658a]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyObject_Call+0x43)[0x7ff3cecc3233]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x18d3)[0x7ff3ced53803]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(+0x6e039)[0x7ff3cece7039]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyObject_Call+0x43)[0x7ff3cecc3233]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(+0x58b7c)[0x7ff3cecd1b7c]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyObject_Call+0x43)[0x7ff3cecc3233]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(+0xa0f93)[0x7ff3ced19f93]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyObject_Call+0x43)[0x7ff3cecc3233]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x18d3)[0x7ff3ced53803]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCode+0x19)[0x7ff3ced5b8f9]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x5cad)[0x7ff3ced57bdd]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(+0x6e039)[0x7ff3cece7039]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyObject_Call+0x43)[0x7ff3cecc3233]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(+0x58b7c)[0x7ff3cecd1b7c]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyObject_Call+0x43)[0x7ff3cecc3233]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(+0xa0f93)[0x7ff3ced19f93]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyObject_Call+0x43)[0x7ff3cecc3233]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x18d3)[0x7ff3ced53803]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x792a)[0x7ff3ced5985a]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(+0x6e039)[0x7ff3cece7039]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyObject_Call+0x43)[0x7ff3cecc3233]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(+0x58b7c)[0x7ff3cecd1b7c]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyObject_Call+0x43)[0x7ff3cecc3233]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(+0xa0c83)[0x7ff3ced19c83]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(+0x9d58a)[0x7ff3ced1658a]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyObject_Call+0x43)[0x7ff3cecc3233]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x18d3)[0x7ff3ced53803]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x792a)[0x7ff3ced5985a]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCode+0x19)[0x7ff3ced5b8f9]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(+0xfb38b)[0x7ff3ced7438b]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyRun_FileExFlags+0x72)[0x7ff3ced754c2]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyRun_SimpleFileExFlags+0xe3)[0x7ff3ced76613]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(Py_Main+0xb4a)[0x7ff3ced880ba]
/nix/store/2kcrj1ksd2a14bm5sky182fv2xwfhfap-glibc-2.26-131/lib/libc.so.6(__libc_start_main+0xf0)[0x7ff3cdf77020]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/bin/python(_start+0x2a)[0x4007aa]
------------------------------------------------------------------------
Attaching gdb to process id 20437.
Cannot find gdb installed
GDB is not installed.
Install gdb for enhanced tracebacks.
------------------------------------------------------------------------

**********************************************************************
    Timed out
**********************************************************************
Tests run before process (pid=20435) timed out:
sage: sage.interacts.debugger.test_function2(2, 3)  # using normal prompt would confuse tests below. ## line 24 ##
(5, 6, True, False)
sage: sig_on_count() # check sig_on/off pairings (virtual doctest) ## line 26 ##
0
sage: sage.interacts.debugger.test_function(2, 3) ## line 37 ##
(5, 6, True, False)
sage: sig_on_count() # check sig_on/off pairings (virtual doctest) ## line 39 ##
0
sage: a = sage0.eval("sage.interacts.debugger.test_function('n', 'm')") ## line 60 ##
------------------------------------------------------------------------
/nix/store/bprqv413l2r68dp3m6y7i693zpzjsjnp-spkg-cysignals-1.6.5/lib/python2.7/site-packages/cysignals/signals.so(+0x53c7)[0x7ff3c98dd3c7]
/nix/store/bprqv413l2r68dp3m6y7i693zpzjsjnp-spkg-cysignals-1.6.5/lib/python2.7/site-packages/cysignals/signals.so(+0x5f55)[0x7ff3c98ddf55]
/nix/store/bprqv413l2r68dp3m6y7i693zpzjsjnp-spkg-cysignals-1.6.5/lib/python2.7/site-packages/cysignals/signals.so(+0x87d7)[0x7ff3c98e07d7]
/nix/store/2kcrj1ksd2a14bm5sky182fv2xwfhfap-glibc-2.26-131/lib/libpthread.so.0(+0x11dd0)[0x7ff3cea6cdd0]
/nix/store/2kcrj1ksd2a14bm5sky182fv2xwfhfap-glibc-2.26-131/lib/libc.so.6(__select+0x17)[0x7ff3ce03e567]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/python2.7/lib-dynload/select.so(+0x337c)[0x7ff3c864237c]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x74e6)[0x7ff3ced59416]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(+0x6e11d)[0x7ff3cece711d]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyObject_Call+0x43)[0x7ff3cecc3233]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x285d)[0x7ff3ced5478d]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(+0x6e11d)[0x7ff3cece711d]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyObject_Call+0x43)[0x7ff3cecc3233]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(+0x58b7c)[0x7ff3cecd1b7c]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyObject_Call+0x43)[0x7ff3cecc3233]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x285d)[0x7ff3ced5478d]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCode+0x19)[0x7ff3ced5b8f9]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x5cad)[0x7ff3ced57bdd]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(+0x6e039)[0x7ff3cece7039]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyObject_Call+0x43)[0x7ff3cecc3233]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(+0x58b7c)[0x7ff3cecd1b7c]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyObject_Call+0x43)[0x7ff3cecc3233]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(+0xa0f93)[0x7ff3ced19f93]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyObject_Call+0x43)[0x7ff3cecc3233]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x18d3)[0x7ff3ced53803]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x792a)[0x7ff3ced5985a]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(+0x6e039)[0x7ff3cece7039]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyObject_Call+0x43)[0x7ff3cecc3233]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(+0x58b7c)[0x7ff3cecd1b7c]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyObject_Call+0x43)[0x7ff3cecc3233]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(+0xa0c83)[0x7ff3ced19c83]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(+0x9d58a)[0x7ff3ced1658a]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyObject_Call+0x43)[0x7ff3cecc3233]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x18d3)[0x7ff3ced53803]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x792a)[0x7ff3ced5985a]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCode+0x19)[0x7ff3ced5b8f9]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(+0xfb38b)[0x7ff3ced7438b]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyRun_FileExFlags+0x72)[0x7ff3ced754c2]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyRun_SimpleFileExFlags+0xe3)[0x7ff3ced76613]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(Py_Main+0xb4a)[0x7ff3ced880ba]
/nix/store/2kcrj1ksd2a14bm5sky182fv2xwfhfap-glibc-2.26-131/lib/libc.so.6(__libc_start_main+0xf0)[0x7ff3cdf77020]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/bin/python(_start+0x2a)[0x4007aa]
------------------------------------------------------------------------
Attaching gdb to process id 20435.
Cannot find gdb installed
GDB is not installed.
Install gdb for enhanced tracebacks.
------------------------------------------------------------------------

**********************************************************************
**********************************************************************
File "/nix/store/zgb4cibb5vx07j4gr892mfcxzcjmdrgw-sage-src-8.1/src/sage/tests/cmdline.py", line 360, in sage.tests.cmdline.test_executable
Failed example:
    print(out)
Expected:
    Debugging requires single-threaded operation, setting number of threads to 1.
    Running doctests with ID...
    Doctesting 1 file.
    sage -t ...
    **********************************************************************
    File "...", line 3, in ...
    Failed example:
        assert True == False
    Exception raised:
        Traceback (most recent call last):
        ...
        AssertionError
    > <doctest ...>(1)<module>()
    -> assert True == False
    (Pdb)
    Documented commands (type help <topic>):
    ========================================
    ...
    **********************************************************************
    File "...", line 4, in ...
    Failed example:
        2 + 2
    Expected:
        5
    Got:
        4
    **********************************************************************
    Previously executed commands:
        s...: assert True == False
    In [1]:
    <BLANKLINE>
    Returning to doctests...
    **********************************************************************
    1 item had failures:
       2 of   3 in ...
        [2 tests, 2 failures, ...]
    ...
Got:
    Debugging requires single-threaded operation, setting number of threads to 1.
    Running doctests with ID 2018-03-07-15-02-14-cc57e52b.
    Using --optional=gmp,sage
    Doctesting 1 file.
    sage -t --warn-long 0.0 /tmp/dot_sage/temp/ArchDesk/22112/tmp_zHPzAM.rst
    **********************************************************************
    File "/tmp/dot_sage/temp/ArchDesk/22112/tmp_zHPzAM.rst", line 3, in tmp_zHPzAM
    Failed example:
        assert True == False
    Exception raised:
        Traceback (most recent call last):
          File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/doctest/forker.py", line 515, in _run
            self.compile_and_execute(example, compiler, test.globs)
          File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/doctest/forker.py", line 885, in compile_and_execute
            exec(compiled, globs)
          File "<doctest tmp_zHPzAM[0]>", line 1, in <module>
            assert True == False
        AssertionError
    > <doctest tmp_zHPzAM[0]>(1)<module>()
    -> assert True == False
    (Pdb) 
    Documented commands (type help <topic>):
    ========================================
    EOF    bt         cont      enable  jump  pp       run      unt   
    a      c          continue  exit    l     q        s        until 
    alias  cl         d         h       list  quit     step     up    
    args   clear      debug     help    n     r        tbreak   w     
    b      commands   disable   ignore  next  restart  u        whatis
    break  condition  down      j       p     return   unalias  where 
    <BLANKLINE>
    Miscellaneous help topics:
    ==========================
    exec  pdb
    <BLANKLINE>
    Undocumented commands:
    ======================
    retval  rv
    <BLANKLINE>
    (Pdb) 
    **********************************************************************
    File "/tmp/dot_sage/temp/ArchDesk/22112/tmp_zHPzAM.rst", line 4, in tmp_zHPzAM
    Failed example:
        2 + 2
    Expected:
        5
    Got:
        4
    **********************************************************************
    Previously executed commands:
        sage: assert True == False
    sage: 
    Returning to doctests...
    **********************************************************************
    1 item had failures:
       2 of   3 in tmp_zHPzAM
        [2 tests, 2 failures, 0.53 s]
    ----------------------------------------------------------------------
    sage -t --warn-long 0.0 /tmp/dot_sage/temp/ArchDesk/22112/tmp_zHPzAM.rst  # 2 doctests failed
    ----------------------------------------------------------------------
    Total time for all tests: 0.6 seconds
        cpu time: 0.5 seconds
        cumulative wall time: 0.5 seconds
    <BLANKLINE>
**********************************************************************
1 item had failures:
   1 of 238 in sage.tests.cmdline.test_executable
    [237 tests, 1 failure, 127.87 s]
    Timed out
**********************************************************************
Tests run before process (pid=22110) timed out:
sage: s = Sage() ## line 306 ##
sage: s.eval("P = DiGraph({1:{1:['x','y','z']}}).path_semigroup().algebra(GF(25,'t'))") ## line 307 ##
------------------------------------------------------------------------
/nix/store/bprqv413l2r68dp3m6y7i693zpzjsjnp-spkg-cysignals-1.6.5/lib/python2.7/site-packages/cysignals/signals.so(+0x53c7)[0x7ff3c98dd3c7]
/nix/store/bprqv413l2r68dp3m6y7i693zpzjsjnp-spkg-cysignals-1.6.5/lib/python2.7/site-packages/cysignals/signals.so(+0x5f55)[0x7ff3c98ddf55]
/nix/store/bprqv413l2r68dp3m6y7i693zpzjsjnp-spkg-cysignals-1.6.5/lib/python2.7/site-packages/cysignals/signals.so(+0x87d7)[0x7ff3c98e07d7]
/nix/store/2kcrj1ksd2a14bm5sky182fv2xwfhfap-glibc-2.26-131/lib/libpthread.so.0(+0x11dd0)[0x7ff3cea6cdd0]
/nix/store/2kcrj1ksd2a14bm5sky182fv2xwfhfap-glibc-2.26-131/lib/libc.so.6(__select+0x17)[0x7ff3ce03e567]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/python2.7/lib-dynload/select.so(+0x337c)[0x7ff3c864237c]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x74e6)[0x7ff3ced59416]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(+0x6e11d)[0x7ff3cece711d]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyObject_Call+0x43)[0x7ff3cecc3233]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x285d)[0x7ff3ced5478d]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(+0x6e11d)[0x7ff3cece711d]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyObject_Call+0x43)[0x7ff3cecc3233]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(+0x58b7c)[0x7ff3cecd1b7c]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyObject_Call+0x43)[0x7ff3cecc3233]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x285d)[0x7ff3ced5478d]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCode+0x19)[0x7ff3ced5b8f9]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x5cad)[0x7ff3ced57bdd]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(+0x6e039)[0x7ff3cece7039]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyObject_Call+0x43)[0x7ff3cecc3233]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(+0x58b7c)[0x7ff3cecd1b7c]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyObject_Call+0x43)[0x7ff3cecc3233]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(+0xa0f93)[0x7ff3ced19f93]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyObject_Call+0x43)[0x7ff3cecc3233]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x18d3)[0x7ff3ced53803]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x792a)[0x7ff3ced5985a]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(+0x6e039)[0x7ff3cece7039]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyObject_Call+0x43)[0x7ff3cecc3233]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(+0x58b7c)[0x7ff3cecd1b7c]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyObject_Call+0x43)[0x7ff3cecc3233]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(+0xa0c83)[0x7ff3ced19c83]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(+0x9d58a)[0x7ff3ced1658a]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyObject_Call+0x43)[0x7ff3cecc3233]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x18d3)[0x7ff3ced53803]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x792a)[0x7ff3ced5985a]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCode+0x19)[0x7ff3ced5b8f9]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(+0xfb38b)[0x7ff3ced7438b]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyRun_FileExFlags+0x72)[0x7ff3ced754c2]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyRun_SimpleFileExFlags+0xe3)[0x7ff3ced76613]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(Py_Main+0xb4a)[0x7ff3ced880ba]
/nix/store/2kcrj1ksd2a14bm5sky182fv2xwfhfap-glibc-2.26-131/lib/libc.so.6(__libc_start_main+0xf0)[0x7ff3cdf77020]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/bin/python(_start+0x2a)[0x4007aa]
------------------------------------------------------------------------
Attaching gdb to process id 22110.
Cannot find gdb installed
GDB is not installed.
Install gdb for enhanced tracebacks.
------------------------------------------------------------------------

**********************************************************************
**********************************************************************
File "/nix/store/zgb4cibb5vx07j4gr892mfcxzcjmdrgw-sage-src-8.1/src/sage/libs/gap/all_documented_functions.py", line 9, in sage.libs.gap.all_documented_functions
Warning, slow doctest:
    from sage.libs.gap.all_documented_functions import *
Test ran for 42.74 s
**********************************************************************
File "/nix/store/zgb4cibb5vx07j4gr892mfcxzcjmdrgw-sage-src-8.1/src/sage/libs/gap/assigned_names.py", line 6, in sage.libs.gap.assigned_names
Warning, slow doctest:
    from sage.libs.gap.assigned_names import KEYWORDS, GLOBALS, FUNCTIONS
Test ran for 44.92 s
**********************************************************************
File "/nix/store/zgb4cibb5vx07j4gr892mfcxzcjmdrgw-sage-src-8.1/src/sage/matrix/matrix_integer_dense_hnf.py", line 1158, in sage.matrix.matrix_integer_dense_hnf.benchmark_hnf
Warning, slow doctest:
    hnf.benchmark_hnf([50,100],32)
Test ran for 35.20 s
**********************************************************************
File "/nix/store/zgb4cibb5vx07j4gr892mfcxzcjmdrgw-sage-src-8.1/src/sage/misc/cython.py", line 410, in sage.misc.cython.?
Failed example:
    cython(os.linesep.join(code))
Expected nothing
Got:
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
**********************************************************************
File "/nix/store/zgb4cibb5vx07j4gr892mfcxzcjmdrgw-sage-src-8.1/src/sage/misc/cython.py", line 422, in sage.misc.cython.?
Failed example:
    cython("# distutils: language = c++\n"+
           "from libcpp.vector cimport vector\n"
           "cdef vector[int] * v = new vector[int](4)\n")
Expected nothing
Got:
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
**********************************************************************
File "/nix/store/zgb4cibb5vx07j4gr892mfcxzcjmdrgw-sage-src-8.1/src/sage/misc/cython.py", line 437, in sage.misc.cython.?
Failed example:
    output = sage.misc.cython.cython("test.pyx", create_local_c_file=True)
Expected nothing
Got:
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
**********************************************************************
1 item had failures:
   3 of  24 in sage.misc.cython.?
    [69 tests, 3 failures, 16.35 s]
**********************************************************************
File "/nix/store/zgb4cibb5vx07j4gr892mfcxzcjmdrgw-sage-src-8.1/src/sage/repl/interpreter.py", line 77, in sage.repl.interpreter
Failed example:
    shell.run_cell('1/0')
Expected:
    ---------------------------------------------------------------------------
    ZeroDivisionError                         Traceback (most recent call last)
    <ipython-input-...> in <module>()
    ----> 1 Integer(1)/Integer(0)
    <BLANKLINE>
    .../src/sage/rings/integer.pyx in sage.rings.integer.Integer.__div__ (.../cythonized/sage/rings/integer.c:...)()
       ...        if type(left) is type(right):
       ...            if mpz_sgn((<Integer>right).value) == 0:
    -> ...                  raise ZeroDivisionError("rational division by zero")
       ...            x = <Rational> Rational.__new__(Rational)
       ...            mpq_div_zz(x.value, (<Integer>left).value, (<Integer>right).value)
    <BLANKLINE>
    ZeroDivisionError: rational division by zero
Got:
    <BLANKLINE>
    ZeroDivisionErrorTraceback (most recent call last)
    <ipython-input-1-72ac74c5f414> in <module>()
    ----> 1 Integer(1)/Integer(0)
    <BLANKLINE>
    /nix/store/zgb4cibb5vx07j4gr892mfcxzcjmdrgw-sage-src-8.1/src/sage/rings/integer.pyx in sage.rings.integer.Integer.__div__ (build/cythonized/sage/rings/integer.c:12928)()
       1858         if type(left) is type(right):
       1859             if mpz_sgn((<Integer>right).value) == 0:
    -> 1860                 raise ZeroDivisionError("rational division by zero")
       1861             x = <Rational> Rational.__new__(Rational)
       1862             mpq_div_zz(x.value, (<Integer>left).value, (<Integer>right).value)
    <BLANKLINE>
    ZeroDivisionError: rational division by zero
**********************************************************************
File "/nix/store/zgb4cibb5vx07j4gr892mfcxzcjmdrgw-sage-src-8.1/src/sage/repl/interpreter.py", line 358, in sage.repl.interpreter.SageTestShell.run_cell
Failed example:
    rc = shell.run_cell('1/0')
Expected:
    ---------------------------------------------------------------------------
    ZeroDivisionError                         Traceback (most recent call last)
    ...
    ZeroDivisionError: rational division by zero
Got:
    <BLANKLINE>
    ZeroDivisionErrorTraceback (most recent call last)
    <ipython-input-1-72ac74c5f414> in <module>()
    ----> 1 Integer(1)/Integer(0)
    <BLANKLINE>
    /nix/store/zgb4cibb5vx07j4gr892mfcxzcjmdrgw-sage-src-8.1/src/sage/rings/integer.pyx in sage.rings.integer.Integer.__div__ (build/cythonized/sage/rings/integer.c:12928)()
       1858         if type(left) is type(right):
       1859             if mpz_sgn((<Integer>right).value) == 0:
    -> 1860                 raise ZeroDivisionError("rational division by zero")
       1861             x = <Rational> Rational.__new__(Rational)
       1862             mpq_div_zz(x.value, (<Integer>left).value, (<Integer>right).value)
    <BLANKLINE>
    ZeroDivisionError: rational division by zero
**********************************************************************
2 items had failures:
   1 of   5 in sage.repl.interpreter
   1 of   6 in sage.repl.interpreter.SageTestShell.run_cell
    [131 tests, 2 failures, 7.63 s]
**********************************************************************
File "/nix/store/zgb4cibb5vx07j4gr892mfcxzcjmdrgw-sage-src-8.1/src/sage/repl/configuration.py", line 14, in sage.repl.configuration
Failed example:
    'In [1]: [False, True]' in output
Expected:
    True
Got:
    False
**********************************************************************
1 item had failures:
   1 of   5 in sage.repl.configuration
    [18 tests, 1 failure, 6.30 s]
    Timed out
**********************************************************************
Tests run before process (pid=13826) timed out:
sage: m = ModularSymbols(389) ## line 6 ##
sage: [(g.degree(), e) for g, e in m.T(2).fcp()] ## line 7 ##
[(1, 1), (1, 2), (2, 2), (3, 2), (6, 2), (20, 2)]
sage: sig_on_count() # check sig_on/off pairings (virtual doctest) ## line 9 ##
0
sage: sage.modular.modsym.tests.Test() ## line 56 ##
Modular symbols testing class
sage: T = sage.modular.modsym.tests.Test(weights=[3,5,7]) ## line 58 ##
sage: T.weights ## line 59 ##
[3, 5, 7]
sage: T = sage.modular.modsym.tests.Test(levels=5) ; T.levels ## line 61 ##
[1, 2, 3, 4, 5]
sage: sig_on_count() # check sig_on/off pairings (virtual doctest) ## line 63 ##
0
sage: sage.modular.modsym.tests.Test().__repr__() ## line 85 ##
'Modular symbols testing class'
sage: sig_on_count() # check sig_on/off pairings (virtual doctest) ## line 87 ##
0
sage: T = sage.modular.modsym.tests.Test(levels=[5],weights=[2], onlychar=True) ## line 97 ##
sage: T._modular_symbols_space() ## line 100 ##
character
level = 5, weight = 2, sign = -1
	 Modular Symbols space of dimension 0 for Gamma_0(5) of weight 2 with sign -1 over Rational Field
Modular Symbols space of dimension 0 for Gamma_0(5) of weight 2 with sign -1 over Rational Field
sage: sig_on_count() # check sig_on/off pairings (virtual doctest) ## line 104 ##
0
sage: sage.modular.modsym.tests.Test()._level_weight_sign() # random ## line 133 ##
level = 8, weight = 2, sign = 0
(8, 2, 0)
sage: sig_on_count() # check sig_on/off pairings (virtual doctest) ## line 136 ##
0
sage: sage.modular.modsym.tests.Test()._modular_symbols_space_gamma0() # random ## line 151 ##
level = 6, weight = 4, sign = -1
Modular Symbols space of dimension 1 for Gamma_0(6) of weight 4 with sign -1 over Rational Field
sage: sig_on_count() # check sig_on/off pairings (virtual doctest) ## line 154 ##
0
sage: sage.modular.modsym.tests.Test()._modular_symbols_space_gamma1() # random ## line 168 ##
level = 13, weight = 3, sign = -1
Modular Symbols space of dimension 14 for Gamma_1(13) of weight 3 with sign -1 and over Rational Field
sage: sig_on_count() # check sig_on/off pairings (virtual doctest) ## line 171 ##
0
sage: sage.modular.modsym.tests.Test()._modular_symbols_space_character() # random ## line 185 ##
level = 9, weight = 4, sign = -1
Modular Symbols space of dimension 2 for Gamma_0(9) of weight 4 with sign -1 over Rational Field
sage: sig_on_count() # check sig_on/off pairings (virtual doctest) ## line 188 ##
0
sage: sage.modular.modsym.tests.Test()._do("random") ## line 203 ##
test_random
Doing random test test_csns_nscs
gamma1
level = 3, weight = 2, sign = 1
	 Modular Symbols space of dimension 1 for Gamma_1(3) of weight 2 with sign 1 and over Rational Field
sage: sig_on_count() # check sig_on/off pairings (virtual doctest) ## line 206 ##
0
sage: sage.modular.modsym.tests.Test().random(1) ## line 220 ##
test_random
Doing random test test_csnew_dimension
character
level = 16, weight = 3, sign = -1
	 Modular Symbols space of dimension 0 and level 16, weight 3, character [1, -1], sign -1, over Rational Field
	time=0.024148	elapsed=0.024165
test_random
Doing random test test_dimension
character
level = 1, weight = 2, sign = 0
	 Modular Symbols space of dimension 0 for Gamma_0(1) of weight 2 with sign 0 over Rational Field
	time=0.012051	elapsed=0.036246
test_random
Doing random test test_decomposition
gamma0
level = 15, weight = 3, sign = -1
	 Modular Symbols space of dimension 0 for Gamma_0(15) of weight 3 with sign -1 over Rational Field
	time=0.006554	elapsed=0.042817
test_random
Doing random test test_cs_dimension
gamma1
level = 11, weight = 3, sign = 1
	 Modular Symbols space of dimension 10 for Gamma_1(11) of weight 3 with sign 1 and over Rational Field
	time=0.022356	elapsed=0.06519
test_random
Doing random test test_decomposition
character
level = 14, weight = 3, sign = 0
	 Modular Symbols space of dimension 0 for Gamma_0(14) of weight 3 with sign 0 over Rational Field
	time=0.011001	elapsed=0.076221
test_random
Doing random test test_csns_nscs
gamma0
level = 7, weight = 4, sign = 0
	 Modular Symbols space of dimension 4 for Gamma_0(7) of weight 4 with sign 0 over Rational Field
	time=0.029876	elapsed=0.106115
test_random
Doing random test test_decomposition
character
level = 10, weight = 4, sign = 0
	 Modular Symbols space of dimension 0 and level 10, weight 4, character [zeta4], sign 0, over Cyclotomic Field of order 4 and degree 2
	time=0.02619	elapsed=0.132332
test_random
Doing random test test_decomposition
gamma0
level = 3, weight = 4, sign = -1
	 Modular Symbols space of dimension 0 for Gamma_0(3) of weight 4 with sign -1 over Rational Field
	time=0.00544	elapsed=0.137791
test_random
Doing random test test_decomposition
gamma1
level = 17, weight = 4, sign = -1
	 Modular Symbols space of dimension 28 for Gamma_1(17) of weight 4 with sign -1 and over Rational Field
	time=0.225629	elapsed=0.363438
test_random
Doing random test test_csns_nscs
gamma1
level = 7, weight = 4, sign = 1
	 Modular Symbols space of dimension 9 for Gamma_1(7) of weight 4 with sign 1 and over Rational Field
	time=0.036366	elapsed=0.399834
test_random
Doing random test test_decomposition
gamma0
level = 6, weight = 2, sign = 1
	 Modular Symbols space of dimension 3 for Gamma_0(6) of weight 2 with sign 1 over Rational Field
	time=0.018045	elapsed=0.417907
test_random
Doing random test test_decomposition
gamma0
level = 4, weight = 3, sign = -1
	 Modular Symbols space of dimension 0 for Gamma_0(4) of weight 3 with sign -1 over Rational Field
	time=0.005722	elapsed=0.42366
test_random
Doing random test test_csnew_dimension
gamma0
level = 9, weight = 4, sign = 0
	 Modular Symbols space of dimension 6 for Gamma_0(9) of weight 4 with sign 0 over Rational Field
	time=0.027693	elapsed=0.451371
test_random
Doing random test test_csnew_dimension
character
level = 18, weight = 3, sign = -1
	 Modular Symbols space of dimension 0 and level 18, weight 3, character [zeta6 - 1], sign -1, over Cyclotomic Field of order 6 and degree 2
	time=0.036982	elapsed=0.488382
test_random
Doing random test test_csns_nscs
character
level = 13, weight = 2, sign = 0
	 Modular Symbols space of dimension 0 and level 13, weight 2, character [-zeta12^3 + zeta12], sign 0, over Cyclotomic Field of order 12 and degree 4
	time=0.017755	elapsed=0.506164
test_random
Doing random test test_decomposition
gamma0
level = 14, weight = 3, sign = -1
	 Modular Symbols space of dimension 0 for Gamma_0(14) of weight 3 with sign -1 over Rational Field
	time=0.00635	elapsed=0.512539
test_random
Doing random test test_csns_nscs
gamma0
level = 18, weight = 2, sign = 0
	 Modular Symbols space of dimension 7 for Gamma_0(18) of weight 2 with sign 0 over Rational Field
	time=0.03259	elapsed=0.545147
test_random
Doing random test test_cs_dimension
gamma1
level = 3, weight = 4, sign = 0
	 Modular Symbols space of dimension 2 for Gamma_1(3) of weight 4 with sign 0 and over Rational Field
	time=0.008678	elapsed=0.553853
test_random
Doing random test test_csnew_dimension
gamma0
level = 5, weight = 4, sign = 1
	 Modular Symbols space of dimension 3 for Gamma_0(5) of weight 4 with sign 1 over Rational Field
	time=0.022085	elapsed=0.575965
test_random
Doing random test test_dimension
character
level = 8, weight = 3, sign = 1
	 Modular Symbols space of dimension 0 for Gamma_0(8) of weight 3 with sign 1 over Rational Field
	time=0.012023	elapsed=0.588015
test_random
Doing random test test_csnew_dimension
character
level = 8, weight = 4, sign = 0
	 Modular Symbols space of dimension 0 and level 8, weight 4, character [-1, 1], sign 0, over Rational Field
	time=0.011995	elapsed=0.600029
test_random
Doing random test test_csnew_dimension
gamma0
level = 3, weight = 2, sign = -1
	 Modular Symbols space of dimension 0 for Gamma_0(3) of weight 2 with sign -1 over Rational Field
	time=0.00427	elapsed=0.604328
test_random
Doing random test test_csns_nscs
character
level = 2, weight = 3, sign = 0
	 Modular Symbols space of dimension 0 for Gamma_0(2) of weight 3 with sign 0 over Rational Field
	time=0.008652	elapsed=0.613001
test_random
Doing random test test_csnew_dimension
gamma1
level = 19, weight = 3, sign = 1
	 Modular Symbols space of dimension 30 for Gamma_1(19) of weight 3 with sign 1 and over Rational Field
	time=0.064314	elapsed=0.677337
test_random
Doing random test test_cs_dimension
character
level = 2, weight = 3, sign = 0
	 Modular Symbols space of dimension 0 for Gamma_0(2) of weight 3 with sign 0 over Rational Field
	time=0.105371	elapsed=0.782735
test_random
Doing random test test_csnew_dimension
gamma0
level = 10, weight = 3, sign = 1
	 Modular Symbols space of dimension 0 for Gamma_0(10) of weight 3 with sign 1 over Rational Field
	time=0.007347	elapsed=0.790103
test_random
Doing random test test_cs_dimension
character
level = 3, weight = 2, sign = -1
	 Modular Symbols space of dimension 0 and level 3, weight 2, character [-1], sign -1, over Rational Field
	time=0.012738	elapsed=0.802861
test_random
Doing random test test_csnew_dimension
gamma1
level = 4, weight = 3, sign = -1
	 Modular Symbols space of dimension 1 for Gamma_1(4) of weight 3 with sign -1 and over Rational Field
	time=0.008513	elapsed=0.811395
test_random
Doing random test test_csns_nscs
character
level = 18, weight = 2, sign = -1
	 Modular Symbols space of dimension 1 and level 18, weight 2, character [zeta6 - 1], sign -1, over Cyclotomic Field of order 6 and degree 2
	time=0.039647	elapsed=0.85107
test_random
Doing random test test_csns_nscs
character
level = 17, weight = 4, sign = -1
	 Modular Symbols space of dimension 4 and level 17, weight 4, character [-zeta4], sign -1, over Cyclotomic Field of order 4 and degree 2
	time=0.042756	elapsed=0.893854
test_random
Doing random test test_dimension
gamma0
level = 16, weight = 2, sign = 1
	 Modular Symbols space of dimension 4 for Gamma_0(16) of weight 2 with sign 1 over Rational Field
	time=0.004442	elapsed=0.898325
test_random
Doing random test test_csns_nscs
character
level = 8, weight = 2, sign = 1
	 Modular Symbols space of dimension 3 for Gamma_0(8) of weight 2 with sign 1 over Rational Field
	time=0.027231	elapsed=0.925573
test_random
Doing random test test_csnew_dimension
character
level = 11, weight = 2, sign = 1
	 Modular Symbols space of dimension 2 for Gamma_0(11) of weight 2 with sign 1 over Rational Field
	time=0.015119	elapsed=0.940722
test_random
Doing random test test_dimension
character
level = 7, weight = 4, sign = -1
	 Modular Symbols space of dimension 0 and level 7, weight 4, character [zeta6], sign -1, over Cyclotomic Field of order 6 and degree 2
	time=0.00761	elapsed=0.948357
test_random
Doing random test test_csns_nscs
gamma0
level = 3, weight = 3, sign = 1
	 Modular Symbols space of dimension 0 for Gamma_0(3) of weight 3 with sign 1 over Rational Field
	time=0.006905	elapsed=0.955281
test_random
Doing random test test_dimension
character
level = 10, weight = 4, sign = 1
	 Modular Symbols space of dimension 6 and level 10, weight 4, character [-1], sign 1, over Rational Field
	time=0.010985	elapsed=0.96629
test_random
Doing random test test_cs_dimension
gamma0
level = 7, weight = 3, sign = -1
	 Modular Symbols space of dimension 0 for Gamma_0(7) of weight 3 with sign -1 over Rational Field
	time=0.005677	elapsed=0.971983
test_random
Doing random test test_decomposition
gamma0
level = 18, weight = 4, sign = 0
	 Modular Symbols space of dimension 18 for Gamma_0(18) of weight 4 with sign 0 over Rational Field
------------------------------------------------------------------------
/nix/store/bprqv413l2r68dp3m6y7i693zpzjsjnp-spkg-cysignals-1.6.5/lib/python2.7/site-packages/cysignals/signals.so(+0x53c7)[0x7ff3c98dd3c7]
/nix/store/bprqv413l2r68dp3m6y7i693zpzjsjnp-spkg-cysignals-1.6.5/lib/python2.7/site-packages/cysignals/signals.so(+0x5f55)[0x7ff3c98ddf55]
/nix/store/bprqv413l2r68dp3m6y7i693zpzjsjnp-spkg-cysignals-1.6.5/lib/python2.7/site-packages/cysignals/signals.so(+0x87d7)[0x7ff3c98e07d7]
/nix/store/2kcrj1ksd2a14bm5sky182fv2xwfhfap-glibc-2.26-131/lib/libpthread.so.0(+0x11dd0)[0x7ff3cea6cdd0]
/nix/store/32z5mi81j7jiwzngg2542snn0gcg293d-spkg-fflas_ffpack-2.2.2/lib/libffpack.so.1(_ZN6FFPACK17CharpolyArithProgIN6Givaro7ModularIddEESt6vectorIdSaIdEEEERNSt7__cxx114listIT0_SaIS9_EEERKT_SC_mNSD_11Element_ptrEmm+0x2dc)[0x7ff3755ba28c]
/nix/store/32z5mi81j7jiwzngg2542snn0gcg293d-spkg-fflas_ffpack-2.2.2/lib/libffpack.so.1(_ZN6FFPACK8CharPolyIN6Givaro7ModularIddEESt6vectorIdSaIdEEEERNSt7__cxx114listIT0_SaIS9_EEERKT_SC_mNSD_11Element_ptrEmNS_19FFPACK_CHARPOLY_TAGE+0xef)[0x7ff3755b9c2f]
/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/libs/linbox/linbox_flint_interface.so(_ZN6LinBox19ChineseRemainderSeqINS_14EarlyMultipCRAIN6Givaro7ModularIddEEEEEclINS2_9givvectorINS2_7IntegerESaIS9_EEENS_22IntegerModularCharpolyINS_10BlasMatrixINS2_5ZRingIS9_EESt6vectorIS9_SA_EEENS_21BlasEliminationTraitsEEENS_19RandomPrimeIteratorEEERT_SN_RT0_RT1_+0x492)[0x7ff37376b2d2]
/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/libs/linbox/linbox_flint_interface.so(_ZN6LinBox8charpolyIN6Givaro9givvectorINS1_7IntegerESaIS3_EEENS_10BlasMatrixINS1_5ZRingIS3_EESt6vectorIS3_S4_EEEEERT_SD_RKT0_RKNS_14RingCategories10IntegerTagERKNS_21BlasEliminationTraitsE+0x1e9)[0x7ff37376bdb9]
/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/libs/linbox/linbox_flint_interface.so(_ZN6LinBox8charpolyINS_10BlasMatrixIN6Givaro5ZRingINS2_7IntegerEEESt6vectorIS4_SaIS4_EEEENS2_9givvectorIS4_S7_EEEERT0_SD_RKT_+0xa2)[0x7ff37376bf82]
/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/libs/linbox/linbox_flint_interface.so(+0x27043)[0x7ff373750043]
/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/matrix/matrix_integer_dense.so(+0x4cf8f)[0x7ff378463f8f]
/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/matrix/matrix_integer_dense.so(+0x4e63b)[0x7ff37846563b]
/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/matrix/matrix_rational_dense.so(+0x9720)[0x7ff3769d5720]
/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/matrix/matrix_rational_dense.so(+0x3a613)[0x7ff376a06613]
/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/matrix/matrix_rational_dense.so(+0x178da)[0x7ff3769e38da]
/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/matrix/matrix2.so(+0x12450)[0x7ff379f7a450]
/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/matrix/matrix2.so(+0x1b63f4)[0x7ff37a11e3f4]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x80be)[0x7ff3ced59fee]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCode+0x19)[0x7ff3ced5b8f9]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x5cad)[0x7ff3ced57bdd]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(+0x6e039)[0x7ff3cece7039]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyObject_Call+0x43)[0x7ff3cecc3233]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(+0x58b7c)[0x7ff3cecd1b7c]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyObject_Call+0x43)[0x7ff3cecc3233]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(+0xa0f93)[0x7ff3ced19f93]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyObject_Call+0x43)[0x7ff3cecc3233]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x18d3)[0x7ff3ced53803]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x792a)[0x7ff3ced5985a]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(+0x6e039)[0x7ff3cece7039]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyObject_Call+0x43)[0x7ff3cecc3233]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(+0x58b7c)[0x7ff3cecd1b7c]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyObject_Call+0x43)[0x7ff3cecc3233]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(+0xa0c83)[0x7ff3ced19c83]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(+0x9d58a)[0x7ff3ced1658a]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyObject_Call+0x43)[0x7ff3cecc3233]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x18d3)[0x7ff3ced53803]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x792a)[0x7ff3ced5985a]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6671)[0x7ff3ced585a1]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8)[0x7ff3ced5b6e8]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyEval_EvalCode+0x19)[0x7ff3ced5b8f9]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(+0xfb38b)[0x7ff3ced7438b]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyRun_FileExFlags+0x72)[0x7ff3ced754c2]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(PyRun_SimpleFileExFlags+0xe3)[0x7ff3ced76613]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/libpython2.7.so.1.0(Py_Main+0xb4a)[0x7ff3ced880ba]
/nix/store/2kcrj1ksd2a14bm5sky182fv2xwfhfap-glibc-2.26-131/lib/libc.so.6(__libc_start_main+0xf0)[0x7ff3cdf77020]
/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/bin/python(_start+0x2a)[0x4007aa]
------------------------------------------------------------------------
Attaching gdb to process id 13826.
Cannot find gdb installed
GDB is not installed.
Install gdb for enhanced tracebacks.
------------------------------------------------------------------------

**********************************************************************
**********************************************************************
File "/nix/store/zgb4cibb5vx07j4gr892mfcxzcjmdrgw-sage-src-8.1/src/sage/ext/stdsage.pxi", line 6, in sage.ext.stdsage
Failed example:
    cython('include "sage/ext/stdsage.pxi"')
Exception raised:
    Traceback (most recent call last):
      File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/doctest/forker.py", line 515, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/doctest/forker.py", line 885, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.ext.stdsage[0]>", line 1, in <module>
        cython('include "sage/ext/stdsage.pxi"')
      File "sage/misc/lazy_import.pyx", line 354, in sage.misc.lazy_import.LazyImport.__call__ (build/cythonized/sage/misc/lazy_import.c:3704)
        return self.get_object()(*args, **kwds)
      File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/misc/cython.py", line 906, in cython_compile
        create_local_c_file=False)
      File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/misc/cython.py", line 816, in cython_import_all
        create_local_c_file=create_local_c_file)
      File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/misc/cython.py", line 793, in cython_import
        **kwds)
      File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/misc/cython.py", line 558, in cython
        quiet=not verbose)
      File "/nix/store/g1w80d8ym05qi4bxj5ih1rfh21v66nsh-python2.7-Cython-0.27.3/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 920, in cythonize
        aliases=aliases)
      File "/nix/store/g1w80d8ym05qi4bxj5ih1rfh21v66nsh-python2.7-Cython-0.27.3/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 815, in create_extension_list
        kwds = deps.distutils_info(file, aliases, base).values
      File "/nix/store/g1w80d8ym05qi4bxj5ih1rfh21v66nsh-python2.7-Cython-0.27.3/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 670, in distutils_info
        return (self.transitive_merge(filename, self.distutils_info0, DistutilsInfo.merge)
      File "/nix/store/g1w80d8ym05qi4bxj5ih1rfh21v66nsh-python2.7-Cython-0.27.3/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 680, in transitive_merge
        node, extract, merge, seen, {}, self.cimported_files)[0]
      File "/nix/store/g1w80d8ym05qi4bxj5ih1rfh21v66nsh-python2.7-Cython-0.27.3/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 685, in transitive_merge_helper
        deps = extract(node)
      File "/nix/store/g1w80d8ym05qi4bxj5ih1rfh21v66nsh-python2.7-Cython-0.27.3/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 650, in distutils_info0
        cimports, externs, incdirs = self.cimports_externs_incdirs(filename)
      File "/nix/store/g1w80d8ym05qi4bxj5ih1rfh21v66nsh-python2.7-Cython-0.27.3/lib/python2.7/site-packages/Cython/Utils.py", line 44, in wrapper
        res = cache[args] = f(self, *args)
      File "/nix/store/g1w80d8ym05qi4bxj5ih1rfh21v66nsh-python2.7-Cython-0.27.3/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 555, in cimports_externs_incdirs
        for include in self.included_files(filename):
      File "/nix/store/g1w80d8ym05qi4bxj5ih1rfh21v66nsh-python2.7-Cython-0.27.3/lib/python2.7/site-packages/Cython/Utils.py", line 44, in wrapper
        res = cache[args] = f(self, *args)
      File "/nix/store/g1w80d8ym05qi4bxj5ih1rfh21v66nsh-python2.7-Cython-0.27.3/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 542, in included_files
        all.update(self.included_files(include_path))
      File "/nix/store/g1w80d8ym05qi4bxj5ih1rfh21v66nsh-python2.7-Cython-0.27.3/lib/python2.7/site-packages/Cython/Utils.py", line 44, in wrapper
        res = cache[args] = f(self, *args)
      File "/nix/store/g1w80d8ym05qi4bxj5ih1rfh21v66nsh-python2.7-Cython-0.27.3/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 537, in included_files
        include_path = self.context.find_include_file(include, None)
      File "/nix/store/g1w80d8ym05qi4bxj5ih1rfh21v66nsh-python2.7-Cython-0.27.3/lib/python2.7/site-packages/Cython/Compiler/Main.py", line 274, in find_include_file
        error(pos, "'%s' not found" % filename)
      File "/nix/store/g1w80d8ym05qi4bxj5ih1rfh21v66nsh-python2.7-Cython-0.27.3/lib/python2.7/site-packages/Cython/Compiler/Errors.py", line 178, in error
        raise InternalError(message)
    InternalError: Internal compiler error: 'cysignals/memory.pxi' not found
**********************************************************************
1 item had failures:
   1 of   2 in sage.ext.stdsage
    [1 test, 1 failure, 0.81 s]
**********************************************************************
File "/nix/store/zgb4cibb5vx07j4gr892mfcxzcjmdrgw-sage-src-8.1/src/sage/misc/compat.py", line 90, in sage.misc.compat
Failed example:
    find_library('Singular')
Expected:
    '...Singular...'
Got:
    <BLANKLINE>
**********************************************************************
1 item had failures:
   1 of   3 in sage.misc.compat
    [2 tests, 1 failure, 0.59 s]
**********************************************************************
File "/nix/store/zgb4cibb5vx07j4gr892mfcxzcjmdrgw-sage-src-8.1/src/sage/repl/ipython_kernel/install.py", line 29, in sage.repl.ipython_kernel.install.SageKernelSpec.__init__
Failed example:
    spec = SageKernelSpec()
Exception raised:
    Traceback (most recent call last):
      File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/doctest/forker.py", line 515, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/doctest/forker.py", line 885, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.repl.ipython_kernel.install.SageKernelSpec.__init__[1]>", line 1, in <module>
        spec = SageKernelSpec()
      File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/repl/ipython_kernel/install.py", line 36, in __init__
        self._mkdirs()
      File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/repl/ipython_kernel/install.py", line 56, in _mkdirs
        mkdir_p(self.nbextensions_dir)
      File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/repl/ipython_kernel/install.py", line 52, in mkdir_p
        os.makedirs(path)
      File "/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/python2.7/os.py", line 150, in makedirs
        makedirs(head, mode)
      File "/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/python2.7/os.py", line 157, in makedirs
        mkdir(name, mode)
    OSError: [Errno 13] Permission denied: '/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/jupyter'
**********************************************************************
File "/nix/store/zgb4cibb5vx07j4gr892mfcxzcjmdrgw-sage-src-8.1/src/sage/repl/ipython_kernel/install.py", line 30, in sage.repl.ipython_kernel.install.SageKernelSpec.__init__
Failed example:
    spec._display_name    # random output
Exception raised:
    Traceback (most recent call last):
      File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/doctest/forker.py", line 515, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/doctest/forker.py", line 885, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.repl.ipython_kernel.install.SageKernelSpec.__init__[2]>", line 1, in <module>
        spec._display_name    # random output
    NameError: name 'spec' is not defined
**********************************************************************
File "/nix/store/zgb4cibb5vx07j4gr892mfcxzcjmdrgw-sage-src-8.1/src/sage/repl/ipython_kernel/install.py", line 45, in sage.repl.ipython_kernel.install.SageKernelSpec._mkdirs
Failed example:
    spec = SageKernelSpec()
Exception raised:
    Traceback (most recent call last):
      File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/doctest/forker.py", line 515, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/doctest/forker.py", line 885, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.repl.ipython_kernel.install.SageKernelSpec._mkdirs[1]>", line 1, in <module>
        spec = SageKernelSpec()
      File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/repl/ipython_kernel/install.py", line 36, in __init__
        self._mkdirs()
      File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/repl/ipython_kernel/install.py", line 56, in _mkdirs
        mkdir_p(self.nbextensions_dir)
      File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/repl/ipython_kernel/install.py", line 52, in mkdir_p
        os.makedirs(path)
      File "/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/python2.7/os.py", line 150, in makedirs
        makedirs(head, mode)
      File "/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/python2.7/os.py", line 157, in makedirs
        mkdir(name, mode)
    OSError: [Errno 13] Permission denied: '/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/jupyter'
**********************************************************************
File "/nix/store/zgb4cibb5vx07j4gr892mfcxzcjmdrgw-sage-src-8.1/src/sage/repl/ipython_kernel/install.py", line 46, in sage.repl.ipython_kernel.install.SageKernelSpec._mkdirs
Failed example:
    spec._mkdirs()
Exception raised:
    Traceback (most recent call last):
      File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/doctest/forker.py", line 515, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/doctest/forker.py", line 885, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.repl.ipython_kernel.install.SageKernelSpec._mkdirs[2]>", line 1, in <module>
        spec._mkdirs()
    NameError: name 'spec' is not defined
**********************************************************************
File "/nix/store/zgb4cibb5vx07j4gr892mfcxzcjmdrgw-sage-src-8.1/src/sage/repl/ipython_kernel/install.py", line 47, in sage.repl.ipython_kernel.install.SageKernelSpec._mkdirs
Failed example:
    os.path.isdir(spec.nbextensions_dir)
Exception raised:
    Traceback (most recent call last):
      File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/doctest/forker.py", line 515, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/doctest/forker.py", line 885, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.repl.ipython_kernel.install.SageKernelSpec._mkdirs[3]>", line 1, in <module>
        os.path.isdir(spec.nbextensions_dir)
    NameError: name 'spec' is not defined
**********************************************************************
File "/nix/store/zgb4cibb5vx07j4gr892mfcxzcjmdrgw-sage-src-8.1/src/sage/repl/ipython_kernel/install.py", line 86, in sage.repl.ipython_kernel.install.SageKernelSpec.symlink
Failed example:
    spec = SageKernelSpec()
Exception raised:
    Traceback (most recent call last):
      File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/doctest/forker.py", line 515, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/doctest/forker.py", line 885, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.repl.ipython_kernel.install.SageKernelSpec.symlink[1]>", line 1, in <module>
        spec = SageKernelSpec()
      File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/repl/ipython_kernel/install.py", line 36, in __init__
        self._mkdirs()
      File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/repl/ipython_kernel/install.py", line 56, in _mkdirs
        mkdir_p(self.nbextensions_dir)
      File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/repl/ipython_kernel/install.py", line 52, in mkdir_p
        os.makedirs(path)
      File "/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/python2.7/os.py", line 150, in makedirs
        makedirs(head, mode)
      File "/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/python2.7/os.py", line 157, in makedirs
        mkdir(name, mode)
    OSError: [Errno 13] Permission denied: '/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/jupyter'
**********************************************************************
File "/nix/store/zgb4cibb5vx07j4gr892mfcxzcjmdrgw-sage-src-8.1/src/sage/repl/ipython_kernel/install.py", line 88, in sage.repl.ipython_kernel.install.SageKernelSpec.symlink
Failed example:
    spec.symlink(os.path.join(path, 'a'), os.path.join(path, 'b'))
Exception raised:
    Traceback (most recent call last):
      File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/doctest/forker.py", line 515, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/doctest/forker.py", line 885, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.repl.ipython_kernel.install.SageKernelSpec.symlink[3]>", line 1, in <module>
        spec.symlink(os.path.join(path, 'a'), os.path.join(path, 'b'))
    NameError: name 'spec' is not defined
**********************************************************************
File "/nix/store/zgb4cibb5vx07j4gr892mfcxzcjmdrgw-sage-src-8.1/src/sage/repl/ipython_kernel/install.py", line 89, in sage.repl.ipython_kernel.install.SageKernelSpec.symlink
Failed example:
    os.listdir(path)
Expected:
    ['b']
Got:
    []
**********************************************************************
File "/nix/store/zgb4cibb5vx07j4gr892mfcxzcjmdrgw-sage-src-8.1/src/sage/repl/ipython_kernel/install.py", line 106, in sage.repl.ipython_kernel.install.SageKernelSpec.use_local_mathjax
Failed example:
    spec = SageKernelSpec()
Exception raised:
    Traceback (most recent call last):
      File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/doctest/forker.py", line 515, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/doctest/forker.py", line 885, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.repl.ipython_kernel.install.SageKernelSpec.use_local_mathjax[1]>", line 1, in <module>
        spec = SageKernelSpec()
      File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/repl/ipython_kernel/install.py", line 36, in __init__
        self._mkdirs()
      File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/repl/ipython_kernel/install.py", line 56, in _mkdirs
        mkdir_p(self.nbextensions_dir)
      File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/repl/ipython_kernel/install.py", line 52, in mkdir_p
        os.makedirs(path)
      File "/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/python2.7/os.py", line 150, in makedirs
        makedirs(head, mode)
      File "/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/python2.7/os.py", line 157, in makedirs
        mkdir(name, mode)
    OSError: [Errno 13] Permission denied: '/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/jupyter'
**********************************************************************
File "/nix/store/zgb4cibb5vx07j4gr892mfcxzcjmdrgw-sage-src-8.1/src/sage/repl/ipython_kernel/install.py", line 107, in sage.repl.ipython_kernel.install.SageKernelSpec.use_local_mathjax
Failed example:
    spec.use_local_mathjax()
Exception raised:
    Traceback (most recent call last):
      File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/doctest/forker.py", line 515, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/doctest/forker.py", line 885, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.repl.ipython_kernel.install.SageKernelSpec.use_local_mathjax[2]>", line 1, in <module>
        spec.use_local_mathjax()
    NameError: name 'spec' is not defined
**********************************************************************
File "/nix/store/zgb4cibb5vx07j4gr892mfcxzcjmdrgw-sage-src-8.1/src/sage/repl/ipython_kernel/install.py", line 108, in sage.repl.ipython_kernel.install.SageKernelSpec.use_local_mathjax
Failed example:
    mathjax = os.path.join(spec.nbextensions_dir, 'mathjax')
Exception raised:
    Traceback (most recent call last):
      File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/doctest/forker.py", line 515, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/doctest/forker.py", line 885, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.repl.ipython_kernel.install.SageKernelSpec.use_local_mathjax[3]>", line 1, in <module>
        mathjax = os.path.join(spec.nbextensions_dir, 'mathjax')
    NameError: name 'spec' is not defined
**********************************************************************
File "/nix/store/zgb4cibb5vx07j4gr892mfcxzcjmdrgw-sage-src-8.1/src/sage/repl/ipython_kernel/install.py", line 109, in sage.repl.ipython_kernel.install.SageKernelSpec.use_local_mathjax
Failed example:
    os.path.isdir(mathjax)
Exception raised:
    Traceback (most recent call last):
      File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/doctest/forker.py", line 515, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/doctest/forker.py", line 885, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.repl.ipython_kernel.install.SageKernelSpec.use_local_mathjax[4]>", line 1, in <module>
        os.path.isdir(mathjax)
    NameError: name 'mathjax' is not defined
**********************************************************************
File "/nix/store/zgb4cibb5vx07j4gr892mfcxzcjmdrgw-sage-src-8.1/src/sage/repl/ipython_kernel/install.py", line 123, in sage.repl.ipython_kernel.install.SageKernelSpec.use_local_jsmol
Failed example:
    spec = SageKernelSpec()
Exception raised:
    Traceback (most recent call last):
      File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/doctest/forker.py", line 515, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/doctest/forker.py", line 885, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.repl.ipython_kernel.install.SageKernelSpec.use_local_jsmol[1]>", line 1, in <module>
        spec = SageKernelSpec()
      File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/repl/ipython_kernel/install.py", line 36, in __init__
        self._mkdirs()
      File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/repl/ipython_kernel/install.py", line 56, in _mkdirs
        mkdir_p(self.nbextensions_dir)
      File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/repl/ipython_kernel/install.py", line 52, in mkdir_p
        os.makedirs(path)
      File "/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/python2.7/os.py", line 150, in makedirs
        makedirs(head, mode)
      File "/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/python2.7/os.py", line 157, in makedirs
        mkdir(name, mode)
    OSError: [Errno 13] Permission denied: '/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/jupyter'
**********************************************************************
File "/nix/store/zgb4cibb5vx07j4gr892mfcxzcjmdrgw-sage-src-8.1/src/sage/repl/ipython_kernel/install.py", line 124, in sage.repl.ipython_kernel.install.SageKernelSpec.use_local_jsmol
Failed example:
    spec.use_local_jsmol()
Exception raised:
    Traceback (most recent call last):
      File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/doctest/forker.py", line 515, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/doctest/forker.py", line 885, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.repl.ipython_kernel.install.SageKernelSpec.use_local_jsmol[2]>", line 1, in <module>
        spec.use_local_jsmol()
    NameError: name 'spec' is not defined
**********************************************************************
File "/nix/store/zgb4cibb5vx07j4gr892mfcxzcjmdrgw-sage-src-8.1/src/sage/repl/ipython_kernel/install.py", line 125, in sage.repl.ipython_kernel.install.SageKernelSpec.use_local_jsmol
Failed example:
    jsmol = os.path.join(spec.nbextensions_dir, 'jsmol')
Exception raised:
    Traceback (most recent call last):
      File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/doctest/forker.py", line 515, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/doctest/forker.py", line 885, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.repl.ipython_kernel.install.SageKernelSpec.use_local_jsmol[3]>", line 1, in <module>
        jsmol = os.path.join(spec.nbextensions_dir, 'jsmol')
    NameError: name 'spec' is not defined
**********************************************************************
File "/nix/store/zgb4cibb5vx07j4gr892mfcxzcjmdrgw-sage-src-8.1/src/sage/repl/ipython_kernel/install.py", line 126, in sage.repl.ipython_kernel.install.SageKernelSpec.use_local_jsmol
Failed example:
    os.path.isdir(jsmol)
Exception raised:
    Traceback (most recent call last):
      File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/doctest/forker.py", line 515, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/doctest/forker.py", line 885, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.repl.ipython_kernel.install.SageKernelSpec.use_local_jsmol[4]>", line 1, in <module>
        os.path.isdir(jsmol)
    NameError: name 'jsmol' is not defined
**********************************************************************
File "/nix/store/zgb4cibb5vx07j4gr892mfcxzcjmdrgw-sage-src-8.1/src/sage/repl/ipython_kernel/install.py", line 140, in sage.repl.ipython_kernel.install.SageKernelSpec.use_local_threejs
Failed example:
    spec = SageKernelSpec()
Exception raised:
    Traceback (most recent call last):
      File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/doctest/forker.py", line 515, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/doctest/forker.py", line 885, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.repl.ipython_kernel.install.SageKernelSpec.use_local_threejs[1]>", line 1, in <module>
        spec = SageKernelSpec()
      File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/repl/ipython_kernel/install.py", line 36, in __init__
        self._mkdirs()
      File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/repl/ipython_kernel/install.py", line 56, in _mkdirs
        mkdir_p(self.nbextensions_dir)
      File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/repl/ipython_kernel/install.py", line 52, in mkdir_p
        os.makedirs(path)
      File "/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/python2.7/os.py", line 150, in makedirs
        makedirs(head, mode)
      File "/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/python2.7/os.py", line 157, in makedirs
        mkdir(name, mode)
    OSError: [Errno 13] Permission denied: '/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/jupyter'
**********************************************************************
File "/nix/store/zgb4cibb5vx07j4gr892mfcxzcjmdrgw-sage-src-8.1/src/sage/repl/ipython_kernel/install.py", line 141, in sage.repl.ipython_kernel.install.SageKernelSpec.use_local_threejs
Failed example:
    spec.use_local_threejs()
Exception raised:
    Traceback (most recent call last):
      File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/doctest/forker.py", line 515, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/doctest/forker.py", line 885, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.repl.ipython_kernel.install.SageKernelSpec.use_local_threejs[2]>", line 1, in <module>
        spec.use_local_threejs()
    NameError: name 'spec' is not defined
**********************************************************************
File "/nix/store/zgb4cibb5vx07j4gr892mfcxzcjmdrgw-sage-src-8.1/src/sage/repl/ipython_kernel/install.py", line 142, in sage.repl.ipython_kernel.install.SageKernelSpec.use_local_threejs
Failed example:
    threejs = os.path.join(spec.nbextensions_dir, 'threejs')
Exception raised:
    Traceback (most recent call last):
      File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/doctest/forker.py", line 515, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/doctest/forker.py", line 885, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.repl.ipython_kernel.install.SageKernelSpec.use_local_threejs[3]>", line 1, in <module>
        threejs = os.path.join(spec.nbextensions_dir, 'threejs')
    NameError: name 'spec' is not defined
**********************************************************************
File "/nix/store/zgb4cibb5vx07j4gr892mfcxzcjmdrgw-sage-src-8.1/src/sage/repl/ipython_kernel/install.py", line 143, in sage.repl.ipython_kernel.install.SageKernelSpec.use_local_threejs
Failed example:
    os.path.isdir(threejs)
Exception raised:
    Traceback (most recent call last):
      File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/doctest/forker.py", line 515, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/doctest/forker.py", line 885, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.repl.ipython_kernel.install.SageKernelSpec.use_local_threejs[4]>", line 1, in <module>
        os.path.isdir(threejs)
    NameError: name 'threejs' is not defined
**********************************************************************
File "/nix/store/zgb4cibb5vx07j4gr892mfcxzcjmdrgw-sage-src-8.1/src/sage/repl/ipython_kernel/install.py", line 161, in sage.repl.ipython_kernel.install.SageKernelSpec._kernel_cmd
Failed example:
    spec = SageKernelSpec()
Exception raised:
    Traceback (most recent call last):
      File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/doctest/forker.py", line 515, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/doctest/forker.py", line 885, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.repl.ipython_kernel.install.SageKernelSpec._kernel_cmd[1]>", line 1, in <module>
        spec = SageKernelSpec()
      File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/repl/ipython_kernel/install.py", line 36, in __init__
        self._mkdirs()
      File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/repl/ipython_kernel/install.py", line 56, in _mkdirs
        mkdir_p(self.nbextensions_dir)
      File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/repl/ipython_kernel/install.py", line 52, in mkdir_p
        os.makedirs(path)
      File "/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/python2.7/os.py", line 150, in makedirs
        makedirs(head, mode)
      File "/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/python2.7/os.py", line 157, in makedirs
        mkdir(name, mode)
    OSError: [Errno 13] Permission denied: '/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/jupyter'
**********************************************************************
File "/nix/store/zgb4cibb5vx07j4gr892mfcxzcjmdrgw-sage-src-8.1/src/sage/repl/ipython_kernel/install.py", line 162, in sage.repl.ipython_kernel.install.SageKernelSpec._kernel_cmd
Failed example:
    spec._kernel_cmd()
Exception raised:
    Traceback (most recent call last):
      File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/doctest/forker.py", line 515, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/doctest/forker.py", line 885, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.repl.ipython_kernel.install.SageKernelSpec._kernel_cmd[2]>", line 1, in <module>
        spec._kernel_cmd()
    NameError: name 'spec' is not defined
**********************************************************************
File "/nix/store/zgb4cibb5vx07j4gr892mfcxzcjmdrgw-sage-src-8.1/src/sage/repl/ipython_kernel/install.py", line 188, in sage.repl.ipython_kernel.install.SageKernelSpec.kernel_spec
Failed example:
    spec = SageKernelSpec()
Exception raised:
    Traceback (most recent call last):
      File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/doctest/forker.py", line 515, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/doctest/forker.py", line 885, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.repl.ipython_kernel.install.SageKernelSpec.kernel_spec[1]>", line 1, in <module>
        spec = SageKernelSpec()
      File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/repl/ipython_kernel/install.py", line 36, in __init__
        self._mkdirs()
      File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/repl/ipython_kernel/install.py", line 56, in _mkdirs
        mkdir_p(self.nbextensions_dir)
      File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/repl/ipython_kernel/install.py", line 52, in mkdir_p
        os.makedirs(path)
      File "/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/python2.7/os.py", line 150, in makedirs
        makedirs(head, mode)
      File "/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/python2.7/os.py", line 157, in makedirs
        mkdir(name, mode)
    OSError: [Errno 13] Permission denied: '/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/jupyter'
**********************************************************************
File "/nix/store/zgb4cibb5vx07j4gr892mfcxzcjmdrgw-sage-src-8.1/src/sage/repl/ipython_kernel/install.py", line 189, in sage.repl.ipython_kernel.install.SageKernelSpec.kernel_spec
Failed example:
    spec.kernel_spec()
Exception raised:
    Traceback (most recent call last):
      File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/doctest/forker.py", line 515, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/doctest/forker.py", line 885, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.repl.ipython_kernel.install.SageKernelSpec.kernel_spec[2]>", line 1, in <module>
        spec.kernel_spec()
    NameError: name 'spec' is not defined
**********************************************************************
File "/nix/store/zgb4cibb5vx07j4gr892mfcxzcjmdrgw-sage-src-8.1/src/sage/repl/ipython_kernel/install.py", line 204, in sage.repl.ipython_kernel.install.SageKernelSpec._install_spec
Failed example:
    spec = SageKernelSpec()
Exception raised:
    Traceback (most recent call last):
      File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/doctest/forker.py", line 515, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/doctest/forker.py", line 885, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.repl.ipython_kernel.install.SageKernelSpec._install_spec[1]>", line 1, in <module>
        spec = SageKernelSpec()
      File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/repl/ipython_kernel/install.py", line 36, in __init__
        self._mkdirs()
      File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/repl/ipython_kernel/install.py", line 56, in _mkdirs
        mkdir_p(self.nbextensions_dir)
      File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/repl/ipython_kernel/install.py", line 52, in mkdir_p
        os.makedirs(path)
      File "/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/python2.7/os.py", line 150, in makedirs
        makedirs(head, mode)
      File "/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/python2.7/os.py", line 157, in makedirs
        mkdir(name, mode)
    OSError: [Errno 13] Permission denied: '/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/jupyter'
**********************************************************************
File "/nix/store/zgb4cibb5vx07j4gr892mfcxzcjmdrgw-sage-src-8.1/src/sage/repl/ipython_kernel/install.py", line 223, in sage.repl.ipython_kernel.install.SageKernelSpec._symlink_resources
Failed example:
    spec = SageKernelSpec()
Exception raised:
    Traceback (most recent call last):
      File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/doctest/forker.py", line 515, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/doctest/forker.py", line 885, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.repl.ipython_kernel.install.SageKernelSpec._symlink_resources[1]>", line 1, in <module>
        spec = SageKernelSpec()
      File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/repl/ipython_kernel/install.py", line 36, in __init__
        self._mkdirs()
      File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/repl/ipython_kernel/install.py", line 56, in _mkdirs
        mkdir_p(self.nbextensions_dir)
      File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/repl/ipython_kernel/install.py", line 52, in mkdir_p
        os.makedirs(path)
      File "/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/python2.7/os.py", line 150, in makedirs
        makedirs(head, mode)
      File "/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/python2.7/os.py", line 157, in makedirs
        mkdir(name, mode)
    OSError: [Errno 13] Permission denied: '/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/jupyter'
**********************************************************************
File "/nix/store/zgb4cibb5vx07j4gr892mfcxzcjmdrgw-sage-src-8.1/src/sage/repl/ipython_kernel/install.py", line 250, in sage.repl.ipython_kernel.install.SageKernelSpec.update
Failed example:
    spec = SageKernelSpec()
Exception raised:
    Traceback (most recent call last):
      File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/doctest/forker.py", line 515, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/doctest/forker.py", line 885, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.repl.ipython_kernel.install.SageKernelSpec.update[1]>", line 1, in <module>
        spec = SageKernelSpec()
      File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/repl/ipython_kernel/install.py", line 36, in __init__
        self._mkdirs()
      File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/repl/ipython_kernel/install.py", line 56, in _mkdirs
        mkdir_p(self.nbextensions_dir)
      File "/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/lib/python2.7/site-packages/sage/repl/ipython_kernel/install.py", line 52, in mkdir_p
        os.makedirs(path)
      File "/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/python2.7/os.py", line 150, in makedirs
        makedirs(head, mode)
      File "/nix/store/n5ql7gyc2sqkji8vabjsyr5awfclrnmb-python-2.7.14/lib/python2.7/os.py", line 157, in makedirs
        mkdir(name, mode)
    OSError: [Errno 13] Permission denied: '/nix/store/brfsyms27zf8plq04dsn8364q0n279n1-sagelib-8.1/jupyter'
**********************************************************************
11 items had failures:
   2 of   4 in sage.repl.ipython_kernel.install.SageKernelSpec.__init__
   1 of   3 in sage.repl.ipython_kernel.install.SageKernelSpec._install_spec
   2 of   4 in sage.repl.ipython_kernel.install.SageKernelSpec._kernel_cmd
   3 of   5 in sage.repl.ipython_kernel.install.SageKernelSpec._mkdirs
   1 of   3 in sage.repl.ipython_kernel.install.SageKernelSpec._symlink_resources
   2 of   4 in sage.repl.ipython_kernel.install.SageKernelSpec.kernel_spec
   3 of   6 in sage.repl.ipython_kernel.install.SageKernelSpec.symlink
   1 of   3 in sage.repl.ipython_kernel.install.SageKernelSpec.update
   4 of   6 in sage.repl.ipython_kernel.install.SageKernelSpec.use_local_jsmol
   4 of   6 in sage.repl.ipython_kernel.install.SageKernelSpec.use_local_mathjax
   4 of   6 in sage.repl.ipython_kernel.install.SageKernelSpec.use_local_threejs
    [43 tests, 27 failures, 0.45 s]
----------------------------------------------------------------------
sage -t --warn-long 32.5 /nix/store/zgb4cibb5vx07j4gr892mfcxzcjmdrgw-sage-src-8.1/src/sage/doctest/forker.py  # Timed out
sage -t --warn-long 32.5 /nix/store/zgb4cibb5vx07j4gr892mfcxzcjmdrgw-sage-src-8.1/src/sage/interfaces/sage0.py  # Timed out
sage -t --warn-long 32.5 /nix/store/zgb4cibb5vx07j4gr892mfcxzcjmdrgw-sage-src-8.1/src/sage/misc/randstate.pyx  # Timed out
sage -t --warn-long 32.5 /nix/store/zgb4cibb5vx07j4gr892mfcxzcjmdrgw-sage-src-8.1/src/sage/interacts/debugger.py  # Timed out
sage -t --warn-long 32.5 /nix/store/zgb4cibb5vx07j4gr892mfcxzcjmdrgw-sage-src-8.1/src/sage/tests/cmdline.py  # 1 doctest failed
sage -t --warn-long 32.5 /nix/store/zgb4cibb5vx07j4gr892mfcxzcjmdrgw-sage-src-8.1/src/sage/quivers/algebra_elements.pxi  # Timed out
sage -t --warn-long 32.5 /nix/store/zgb4cibb5vx07j4gr892mfcxzcjmdrgw-sage-src-8.1/src/sage/misc/cython.py  # 3 doctests failed
sage -t --warn-long 32.5 /nix/store/zgb4cibb5vx07j4gr892mfcxzcjmdrgw-sage-src-8.1/src/sage/repl/interpreter.py  # 2 doctests failed
sage -t --warn-long 32.5 /nix/store/zgb4cibb5vx07j4gr892mfcxzcjmdrgw-sage-src-8.1/src/sage/repl/configuration.py  # 1 doctest failed
sage -t --warn-long 32.5 /nix/store/zgb4cibb5vx07j4gr892mfcxzcjmdrgw-sage-src-8.1/src/sage/modular/modsym/tests.py  # Timed out
sage -t --warn-long 32.5 /nix/store/zgb4cibb5vx07j4gr892mfcxzcjmdrgw-sage-src-8.1/src/sage/ext/stdsage.pxi  # 1 doctest failed
sage -t --warn-long 32.5 /nix/store/zgb4cibb5vx07j4gr892mfcxzcjmdrgw-sage-src-8.1/src/sage/misc/compat.py  # 1 doctest failed
sage -t --warn-long 32.5 /nix/store/zgb4cibb5vx07j4gr892mfcxzcjmdrgw-sage-src-8.1/src/sage/repl/ipython_kernel/install.py  # 27 doctests failed
----------------------------------------------------------------------
Total time for all tests: 2416.0 seconds
    cpu time: 5165.4 seconds
    cumulative wall time: 7421.8 seconds
